FarmLegal = {
    Recolte = {
        {
            job = "abatoire",
            point = vector3(-62.40794, 6241.782, 31.09008),
            item = "poulet", itemLabel = "Poulet", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ des ~b~poulets~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer des poulets", description = "Récupérer des poulets"
        },
        
        {
            job = "abatoire",
            point = vector3(-62.40794, 6241.782, 31.09008),
            item = "poulet", itemLabel = "Poulet", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ des ~b~poulets~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer des poulets", description = "Récupérer des poulets"
        },
        {
            job = "couture",
            point = vector3(1978.79, 5171.402, 47.63912),
            item = "pelote_laine", itemLabel = "Pelote de laine", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ des ~b~pelotes de laine~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer des pelotes de laine", description = "Récupérer des pelotes de laine"
        },
        {
            job = "vigneron",
            point = vector3(-1809.734, 2168.664, 109.9464),
            item = "grappe_raisin", itemLabel = "Grappe de raisin", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~grappes de raisin~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 11.0, rotY = -7.0, rotX = -28.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récolter des grappes de raisin", description = "Récolter des grappes de raisin"
        },
        {
            job = "tabac",
            point = vector3(2860.444, 4604.958, 47.91728),
            item = "feuille_tabac", itemLabel = "Feuille de tabac", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~Feuilles de tabac~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récolter des feuilles de tabac", description = "Récolter des feuilles de tabac"
        },
        {
            job = "tacos",
            point = vec3(-152.910828, 6140.479004, 32.335106),
            item = "barquette_poulet", itemLabel = "Barquette de poulet", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ des ~b~barquettes de poulet~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer des barquettes de poulet", description = "Récupérer des barquettes de poulet"
        },
        {
            job = "koi",
            point = vec3(-308.517730, -2764.135742, 4.994704),
            item = "daurade", itemLabel = "Daurade ", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ des ~b~daurades~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer des daurades", description = "Récupérer des daurades"
        },
        {
            job = "horny",
            point = vec3(-152.910828, 6140.479004, 32.335106),
            item = "barquette_poulet", itemLabel = "Barquette de poulet", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ des ~b~barquettes de poulet~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer des barquettes de poulet", description = "Récupérer des barquettes de poulet"
        },
        {
            job = "bahamas",
            point = vector3(282.069, 6507.028, 30.1298),
            item = "fruit_fermente", itemLabel = "Fruit fermenté", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~fruits fermenté~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récolter des fruits fermenté", description = "Récolter des fruits fermenté"
        },
        {
            job = "yellowjack",
            point = vector3(261.554, 6527.214, 30.73818),
            item = "fruit_fermente", itemLabel = "Fruit fermenté", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~fruits fermenté~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récolter des fruits fermenté", description = "Récolter des fruits fermenté"
        },
        {
            job = "tequilala",
            point = vector3(208.5598, 6509.532, 31.47068),
            item = "fruit_fermente", itemLabel = "Fruit fermenté", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~fruits fermenté~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récolter des fruits fermenté", description = "Récolter des fruits fermenté"
        },
        {
            job = "unicorn",
            point = vector3(236.6606, 6502.404, 31.2043),
            item = "fruit_fermente", itemLabel = "Fruit fermenté", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~fruits fermenté~s~",
            ssizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récolter des fruits fermenté", description = "Récolter des fruits fermenté"
        },
        {
            job = "mineur",
            point = vector3(-588.5792, 2065.57, 131.0156),
            item = "pierre_beryl", itemLabel = "Pierre de beryl", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~miner~s~ des ~b~pierres de beryl~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0005,
            Button = "Miner des pierres de beryl", description = "Miner des pierres de beryl"
        },
        {
            job = "burgershot",
            point = vector3(968.2016, -2111.208, 31.47526),
            item = "paquet_viande", itemLabel = "Paquet de viande", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ des ~b~paquets de viande~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer des paquets de viande", description = "Récupérer des paquets de viande"
        },
        {
            job = "uwucafe",
            point = vector3(416.206910, 6520.778320, 27.728448),
            item = "sac_farine", itemLabel = "Sac de farine", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ des ~b~sacs de farine~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer des sacs de farine", description = "Récupérer des sacs de farine"
        },
        {
            job = "nikkibeach",
            point = vector3(219.966186, 6499.898438, 31.384312),
            item = "fruit_fermente", itemLabel = "Fruit fermenté", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~fruits fermenté~s~",
            ssizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récolter des fruits fermenté", description = "Récolter des fruits fermenté"
        },
        {
            job = "henhouse",
            point = vector3(1208.745362, 1855.302490, 78.911568),
            item = "boeuf", itemLabel = "Boeuf", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ de la ~b~viande de boeuf~s~",
            ssizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer de la viande de boeuf", description = "Récupérer de la viande de boeuf"
        },
        {
            job = "torcedor",
            point = vector3(5405.209472, -5213.255860, 34.148774),
            item = "feuille_cigare", itemLabel = "Feuille de cigare", itemReward = 1,
            maxDistMarker = 20, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~feuilles de cigare~s~",
            ssizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récolter des feuilles de cigare", description = "Récolter des feuilles de cigare"
        }
    },
    Traitement = {
        {
            job = "abatoire",
            point = vector3(-78.12636, 6229.496, 31.09186),
            itemNeed = "poulet", itemNeedLabel = "Poulet", itemRemove = 1, itemMini = 1,
            itemNameReward = "cuisse_poulet", itemRewardLabel = "Cuisse de poulet", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~traiter~s~ les ~b~cuisses de poulet~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Traitement de cuisse de poulet", description = "Traiter des cuisses de poulet"
        },
        {
            job = "abatoire",
            point = vector3(-101.8578, 6208.85, 31.02502),
            itemNeed = "cuisse_poulet", itemNeedLabel = "Cuisse de poulet", itemRemove = 5, itemMini = 5,
            itemNameReward = "barquette_poulet", itemRewardLabel = "Barquette de poulet", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre~s~ en ~b~barquette~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Mettre en barquette", description = "Mise des cuisses de poulet en barquette"
        },
        {
            job = "couture",
            point = vector3(714.8238, -969.9232, 30.39532),
            itemNeed = "pelote_laine", itemNeedLabel = "Pelote de laine", itemRemove = 1, itemMini = 1,
            itemNameReward = "tissu", itemRewardLabel = "Tissu", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~traiter~s~ les ~b~pelotes de laine~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Traitement des pelotes de laine", description = "Traiter des pelotes de laine"
        },
        {
            job = "couture",
            point = vector3(716.3384, -960.1016, 30.39532),
            itemNeed = "tissu", itemNeedLabel = "Tissu", itemRemove = 5, itemMini = 5,
            itemNameReward = "vetement", itemRewardLabel = "Vêtement", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~coudre~s~ le ~b~vêtement~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Coudre les vêtement", description = "Coudre les tissu en vêtement"
        },
        {
            job = "vigneron",
            point = vector3(-1931.866, 2055.38, 140.80),
            itemNeed = "grappe_raisin", itemNeedLabel = "Grappe de raisin", itemRemove = 1, itemMini = 1,
            itemNameReward = "jus_raisin", itemRewardLabel = "Jus de raisin", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~traiter~s~ les ~b~grappe de raisin~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Traiter les grappe de raisin", description = "Traiter les grappe de raisin en jus de raisin"
        },
        {
            job = "vigneron",
            point = vector3(-1867.29, 2056.068, 141),
            itemNeed = "jus_raisin", itemNeedLabel = "Jus de raisin", itemRemove = 5, itemMini = 5,
            itemNameReward = "bouteille_vin", itemRewardLabel = "Bouteille de vin", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre~s~ en ~b~bouteille de vin~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0,  
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Mise en bouteille", description = "Mettre le jus de raisin en bouteille de vin"
        },
        {
            job = "tabac",
            point = vector3(2899.868, 4489.966, 48.19),
            itemNeed = "feuille_tabac", itemNeedLabel = "Feuille de tabac", itemRemove = 1, itemMini = 1,
            itemNameReward = "feuille_tabac_seche", itemRewardLabel = "Feuille de tabac séchée", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ les ~b~feuilles de tabac séchée~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer les feuilles de tabac", description = "Récupérer les feuilles de tabac séchée"
        },
        {
            job = "tabac",
            point = vector3(2923.578, 4473.752, 48.16),
            itemNeed = "feuille_tabac_seche", itemNeedLabel = "Feuille de tabac séché", itemRemove = 5, itemMini = 5,
            itemNameReward = "paquet_marlboro", itemRewardLabel = "Paquet de Marlboro", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre~s~ en ~b~paquets de marlboro~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Mise en paquet de marlboro", description = "Mettre les feuilles de tabac séchée en paquets de marlboro"
        },
        {
            job = "burgershot",
            point = vector3(1594.531982, 3748.912354, 34.44),
            itemNeed = "paquet_viande", itemNeedLabel = "Paquet de viande", itemRemove = 1, itemMini = 1,
            itemNameReward = "viande_cuite", itemRewardLabel = "Viande cuite", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~cuire~s~ les ~b~paquets de viandes~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Cuire les paquets de viandes", description = "Cuire les paquets de viande"
        },
        {
            job = "burgershot",
            point = vector3(1592.147950, 3754.521728, 34.44),
            itemNeed = "viande_cuite", itemNeedLabel = "Viande cuite", itemRemove = 5, itemMini = 5,
            itemNameReward = "hamburger", itemRewardLabel = "Hamburger", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~faire~s~ un ~b~hamburger~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Faire un hamburger", description = "Faire un hamburger avec la viande cuite"
        },
        {
            job = "horny",
            point = vector3(1253.578002, -352.360778, 69.085),
            itemNeed = "barquette_poulet", itemNeedLabel = "Barquette de poulet", itemRemove = 1, itemMini = 1,
            itemNameReward = "pouletpane", itemRewardLabel = "Poulet pané", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~cuire~s~ les ~b~barquettes de poulet~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Cuire les barquettes de poulet", description = "Cuire les barquettes de poulet"
        },
        {
            job = "horny",
            point = vector3(1252.142456, -355.584504, 69.085),
            itemNeed = "pouletpane", itemNeedLabel = "Poulet pané", itemRemove = 5, itemMini = 5,
            itemNameReward = "chickenburger", itemRewardLabel = "ChickenBurger", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~faire~s~ un ~b~chickenburger~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Faire un chickenburger", description = "Faire un chickenburger avec le poulet pané"
        },
        {
            job = "tacos",
            point = vector3(424.621308, -1920.064454, 25.48),
            itemNeed = "barquette_poulet", itemNeedLabel = "Barquette de poulet", itemRemove = 1, itemMini = 1,
            itemNameReward = "poulet_cuit", itemRewardLabel = "Poulet cuit", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~cuire~s~ les ~b~cuisses de poulet~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Cuire les cuisses de poulet", description = "Cuire les cuisses de poulet"
        },
        {
            job = "tacos",
            point = vector3(426.892456, -1917.868286, 25.48),
            itemNeed = "poulet_cuit", itemNeedLabel = "Poulet cuit", itemRemove = 5, itemMini = 5,
            itemNameReward = "tacos", itemRewardLabel = "Tacos", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~faire~s~ un ~b~tacos~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Faire un tacos", description = "Faire un tacos avec le poulet cuit"
        },
        {
            job = "koi",
            point = vector3(-1078.048340, -1445.651368, -1.40),
            itemNeed = "daurade", itemNeedLabel = "Daurade", itemRemove = 1, itemMini = 1,
            itemNameReward = "daurade_preparer", itemRewardLabel = "Daurade préparé", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~préparer~s~ les ~b~daurades~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Préparer les daurades", description = "Préparer les daurades"
        },
        {
            job = "koi",
            point = vector3(-1075.533814, -1446.681762, -1.40),
            itemNeed = "daurade_preparer", itemNeedLabel = "Daurade préparé", itemRemove = 5, itemMini = 5,
            itemNameReward = "sushi", itemRewardLabel = "Sushi", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~faire~s~ un ~b~sushi~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Faire un sushi", description = "Faire un sushi avec les daurades préparée"
        },
        {
            job = "bahamas",
            point = vector3(839.5238, 2176.768, 52.29),
            itemNeed = "fruit_fermente", itemNeedLabel = "Fruit fermenté", itemRemove = 1, itemMini = 1,
            itemNameReward = "alcool", itemRewardLabel = "Alcool", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 3, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~fermenter~s~ l'~b~alcool~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0,  
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Fermenter l'alcool", description = "Fermenter l'alcool avec les fruits fermenté"
        },
        {
            job = "bahamas",
            point = vector3(846.2992, 2136.368, 52.865),
            itemNeed = "alcool", itemNeedLabel = "Alcool", itemRemove = 5, itemMini = 5,
            itemNameReward = "bouteille_champagne", itemRewardLabel = "Bouteille de champagne", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre~s~ en ~b~bouteille de champagne~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Mettre en bouteille de champagne", description = "Mettre l'alcool en bouteille de champagne"
        },
        {
            job = "yellowjack",
            point = vector3(839.5238, 2176.768, 52.29),
            itemNeed = "fruit_fermente", itemNeedLabel = "Fruit fermenté", itemRemove = 1, itemMini = 1,
            itemNameReward = "alcool", itemRewardLabel = "Alcool", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 3, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~fermenter~s~ l'~b~alcool~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Fermenter l'alcool", description = "Fermenter l'alcool avec les fruits fermenté"
        },
        {
            job = "yellowjack",
            point = vector3(846.2992, 2136.368, 52.865),
            itemNeed = "alcool", itemNeedLabel = "Alcool", itemRemove = 5, itemMini = 5,
            itemNameReward = "bouteille_whisky", itemRewardLabel = "Bouteille de whisky", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre~s~ en ~b~bouteille de whisky~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Mettre en bouteille de whisky", description = "Mettre l'alcool en bouteille de whisky"
        },
        {
            job = "unicorn",
            point = vector3(839.5238, 2176.768, 52.29),
            itemNeed = "fruit_fermente", itemNeedLabel = "Fruit fermenté", itemRemove = 1, itemMini = 1,
            itemNameReward = "alcool", itemRewardLabel = "Alcool", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 3, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~fermenter~s~ l'~b~alcool~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Fermenter l'alcool", description = "Fermenter l'alcool avec les fruits fermenté"
        },
        {
            job = "unicorn",
            point = vector3(846.2992, 2136.368, 52.865),
            itemNeed = "alcool", itemNeedLabel = "Alcool", itemRemove = 5, itemMini = 5,
            itemNameReward = "bouteille_vodka", itemRewardLabel = "Bouteille de vodka", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre~s~ en ~b~bouteille de vodka~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Mettre en bouteille de vodka", description = "Mettre l'alcool en bouteille de vodka"
        },
        {
            job = "tequilala",
            point = vector3(839.5238, 2176.768, 52.29),
            itemNeed = "fruit_fermente", itemNeedLabel = "Fruit fermenté", itemRemove = 1, itemMini = 1,
            itemNameReward = "alcool", itemRewardLabel = "Alcool", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 3, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~fermenter~s~ l'~b~alcool~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Fermenter l'alcool", description = "Fermenter l'alcool avec les fruits fermenté"
        },
        {
            job = "tequilala",
            point = vector3(846.2992, 2136.368, 52.865),
            itemNeed = "alcool", itemNeedLabel = "Alcool", itemRemove = 5, itemMini = 5,
            itemNameReward = "bouteille_tequila", itemRewardLabel = "Bouteille de tequila", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre~s~ en ~b~bouteille de tequila~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Mettre en bouteille de tequila", description = "Mettre l'alcool en bouteille de tequila"
        },
        {
            job = "mineur",
            point = vector3(2527.674560, 4121.752930, 38.93),
            itemNeed = "pierre_beryl", itemNeedLabel = "Pierre de Beryl", itemRemove = 1, itemMini = 1,
            itemNameReward = "beryl", itemRewardLabel = "Beryl", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~extraire~s~ le ~b~beryl~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0005,
            Button = "Extraire le beryl", description = "Extraire le beryl de la pierre de Beryl"
        },
        {
            job = "mineur",
            point = vector3(2530.941406, 4118.437012, 38.93),
            itemNeed = "beryl", itemNeedLabel = "Beryl", itemRemove = 5, itemMini = 5,
            itemNameReward = "emeraude", itemRewardLabel = "Emeraude", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~soustraire~s~ l'~b~émeraude~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0005,
            Button = "Soustraire l'émeraude", description = "Soustraire l'émeraude du beryl"
        },
        {
            job = "uwucafe",
            point = vector3(-590.477294, -1056.531616, 22.365),
            itemNeed = "sac_farine", itemNeedLabel = "Sac de farine", itemRemove = 1, itemMini = 1,
            itemNameReward = "brownie_moule", itemRewardLabel = "brownie en moule", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~préparer~s~ des ~b~brownies~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Préparer des brownies", description = "Préparer des brownies avec la farine"
        },
        {
            job = "uwucafe",
            point = vector3(-590.279114, -1059.745972, 22.36),
            itemNeed = "brownie_moule", itemNeedLabel = "brownie en moule", itemRemove = 5, itemMini = 5,
            itemNameReward = "brownie", itemRewardLabel = "Brownie", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~cuire~s~ les ~b~brownies en moule~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Cuire les brownies en moule", description = "Cuire les brownies en moule dans le four"
        },
        {
            job = "nikkibeach",
            point = vector3(839.5238, 2176.768, 52.29),
            itemNeed = "fruit_fermente", itemNeedLabel = "Fruit fermenté", itemRemove = 1, itemMini = 1,
            itemNameReward = "alcool", itemRewardLabel = "Alcool", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 3, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~fermenter~s~ l'~b~alcool~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0,  
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Fermenter l'alcool", description = "Fermenter l'alcool avec les fruits fermenté"
        },
        {
            job = "nikkibeach",
            point = vector3(846.2992, 2136.368, 52.865),
            itemNeed = "alcool", itemNeedLabel = "Alcool", itemRemove = 5, itemMini = 5,
            itemNameReward = "frozen_margarita", itemRewardLabel = "Frozen Margarita", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~faire~s~ un cocktail de ~b~frozen margarita~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Faire un cocktail de frozen margarita", description = "Faire un cocktail de frozen margarita"
        },
        {
            job = "henhouse",
            point = vector3(-298.157104, 6271.590820, 31.485),
            itemNeed = "boeuf", itemNeedLabel = "Boeuf", itemRemove = 1, itemMini = 1,
            itemNameReward = "boeuf_cru", itemRewardLabel = "Boeuf cru", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 3, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~préparer~s~ la ~b~viande de boeuf~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0,  
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Préparer la viande de boeuf", description = "Préparer la viande de boeuf"
        },
        {
            job = "henhouse",
            point = vector3(-299.226806, 6270.416504, 31.485),
            itemNeed = "boeuf_cru", itemNeedLabel = "Boeuf cru", itemRemove = 5, itemMini = 5,
            itemNameReward = "boeuf_cuit", itemRewardLabel = "Tomahawk de boeuf", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~préparer~s~ la ~b~tomahawk de boeuf~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Préparer le tomahawk de boeuf", description = "Préparer le tomahawk de boeuf"
        },
        {
            job = "torcedor",
            point = vector3(5212.723632, -5203.679688, 15.83),
            itemNeed = "feuille_cigare", itemNeedLabel = "Feuille de cigare", itemRemove = 1, itemMini = 1,
            itemNameReward = "feuille_cigare_seche", itemRewardLabel = "Feuille de cigare séchée", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~récupérer~s~ les ~b~feuilles de cigare séchée~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Récupérer les Feuilles de cigare séchée", description = "Récupérer les Feuilles de cigare séchée"
        },
        {
            job = "torcedor",
            point = vector3(5092.576172, -4683.177734, 2.407830),
            itemNeed = "feuille_cigare_seche", itemNeedLabel = "Feuille de cigare séchée", itemRemove = 5, itemMini = 5,
            itemNameReward = "paquet_cigare", itemRewardLabel = "Paquet de marlboro", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 1, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre~s~ en ~b~paquets de cigare~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Mise en paquet de cigare", description = "Mettre les feuilles de cigare séchée en paquets de cigare"
        },
    },
    Revente = {
        {
            job = "abatoire",
            society = "society_abatoire",
            point = vector3(-591.47, -892.6196, 25.94376),
            itemNeed = "barquette_poulet", itemNeedLabel = "barquette_poulet", itemRemove = 1, itemMini = 1, moneyReward = 4,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~barquettes de poulet~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les barquette de poulet", description = "Vendre les ~b~barquette de poulet ~s~pour ~g~4$~s~. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "couture",
            society = "society_couture",
            point = vector3(-822.647, -1069.402, 11.32812),
            itemNeed = "vetement", itemNeedLabel = "Vêtement", itemRemove = 1, itemMini = 1, moneyReward = 4,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~vêtements~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les vêtements", description = "Vendre les ~b~vêtements ~s~pour ~g~4$~s~. ~g~(-50% pour l'entreprise)$"
        },
        {
            job = "vigneron",
            society = "society_vigneron",
            point = vector3(-157.901, -54.42962, 54.42),
            itemNeed = "bouteille_vin", itemNeedLabel = "Bouteille de vin", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~bouteilles de vin~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les bouteilles de vin", description = "Vendre les ~b~bouteilles de vin ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "tabac",
            society = "society_tabac",
            point = vector3(-1224.198, -711.0584, 22.345),
            itemNeed = "paquet_marlboro", itemNeedLabel = "Paquet de marlboro", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~paquets de marlboro~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les paquets de marlboro", description = "Vendre les ~b~paquets de marlboro ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "tacos",
            society = "society_tacos",
            point = vector3(-1630.352, -1075.72, 13.09),
            itemNeed = "tacos", itemNeedLabel = "Tacos", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~tacos~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les tacos", description = "Vendre les ~b~tacos ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "koi",
            society = "society_koi",
            point = vector3(-1220.252198, -1504.631592, 4.37),
            itemNeed = "sushi", itemNeedLabel = "Sushi", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~sushi~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les sushi", description = "Vendre les ~b~sushi ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "burgershot",
            society = "society_burgershot",
            point = vector3(1590.796875, 6461.816406, 25.32),
            itemNeed = "hamburger", itemNeedLabel = "Hamburger", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~hamburgers~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les hamburgers", description = "Vendre les ~b~hamburgers ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "horny",
            society = "society_horny",
            point = vector3(-1692.113404, -1136.089112, 13.152318),
            itemNeed = "chickenburger", itemNeedLabel = "ChickenBurger", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~chickenburgers~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les chickenburgers", description = "Vendre les ~b~chickenburgers ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "bahamas",
            society = "society_bahamas",
            point = vector3(-1220.542, -911.578, 12.32634),
            itemNeed = "bouteille_champagne", itemNeedLabel = "Bouteille de champagne", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~bouteille de champagne~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les bouteilles de champagne", description = "Vendre les ~b~bouteilles de champagne ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "unicorn",
            society = "society_unicorn",
            point = vector3(1130.728, -982.7072, 46.4158),
            itemNeed = "bouteille_vodka", itemNeedLabel = "Bouteille de vodka", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~bouteille de vodka~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les bouteilles de vodka", description = "Vendre les ~b~bouteilles de vodka ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "tequilala",
            society = "society_tequilala",
            point = vector3(376.3674, 333.7366, 103.5664),
            itemNeed = "bouteille_tequila", itemNeedLabel = "Bouteille de tequila", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~bouteille de tequila~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les bouteilles de tequila", description = "Vendre les ~b~bouteilles de tequila ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "yellowjack",
            society = "society_yellowjack",
            point = vector3(1166.272, 2714.342, 38.158),
            itemNeed = "bouteille_whisky", itemNeedLabel = "Bouteille de whisky", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~bouteille de whisky~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les bouteilles de whisky", description = "Vendre les ~b~bouteilles de whisky ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "mineur",
            society = "society_mineur",
            point = vector3(-482.3258, -63.40806, 39.99424),
            itemNeed = "emeraude", itemNeedLabel = "Emeraude", itemRemove = 1, itemMini = 1, moneyReward = 240,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~emeraudes~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les emeraudes", description = "Vendre les ~b~émeraudes ~s~pour ~g~240$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "uwucafe",
            society = "society_uwucafe",
            point = vector3(-1707.989624, -1099.523072, 13.152440),
            itemNeed = "brownie", itemNeedLabel = "Brownie", itemRemove = 1, itemMini = 1, moneyReward = 240,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~brownies~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les brownies", description = "Vendre les ~b~brownies ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "nikkibeach",
            society = "society_nikkibeach",
            point = vector3(-2962.888672, 389.910156, 15.043300),
            itemNeed = "frozen_margarita", itemNeedLabel = "Frozen Margarita", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~frozen margarita~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les cocktails de frozen margarita", description = "Vendre les ~b~cocktails de frozen margarita ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "henhouse",
            society = "society_henhouse",
            point = vector3(1983.643554, 3705.186768, 32.566712),
            itemNeed = "boeuf_cuit", itemNeedLabel = "Tomahawk de boeuf", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ la ~b~tomahawk de boeuf~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre la tomahawk de boeuf", description = "Vendre la ~b~tomahawks de boeuf ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        },
        {
            job = "torcedor",
            society = "society_torcedor",
            point = vector3(5137.079590, -5116.730468, 2.13),
            itemNeed = "paquet_cigare", itemNeedLabel = "Paquet de cigare", itemRemove = 1, itemMini = 1, moneyReward = 10,
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~vendre~s~ les ~b~paquets de cigare~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            speedFarm = 0.0040,
            Button = "Vendre les paquets de cigare", description = "Vendre les ~b~paquets de cigare ~s~pour ~g~10$. ~g~(-50% pour l'entreprise)"
        }
    }
}