PercentageResell = {}

PercentageResell.percentProvider = 0.15
PercentageResell.percentReseller = 0.30
PercentageResell.percentSociety = 0.55

VenteLTD = {
    {
        job = "horny",
        society = "society_horny",
        point = vector3(1248.893432, -358.249206, 69.1),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(1254.735230, -359.068878, 69.1),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "chickenburger", label = "ChickenBurger [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
            {name = "longchicken", label = "Long Chicken", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "frite", label = "Frite", price = 5, MaxList = 50, Index = 1, GetItem = false},
            {name = "potatoes", label = "Potatoes", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "horny",
        society = "society_horny",
        point = vector3(1252.662476, -358.593688, 69.1),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~drive",
        pointRecette = vector3(1243.609498, -358.623992, 69.1),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "chickenburger", label = "ChickenBurger [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
            {name = "longchicken", label = "Long Chicken", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "frite", label = "Frite", price = 5, MaxList = 50, Index = 1, GetItem = false},
            {name = "potatoes", label = "Potatoes", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "burgershot",
        society = "society_burgershot",
        point = vector3(1589.757202, 3752.512696, 34.44),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(1588.691528, 3751.657226, 34.44),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "hamburger", label = "Hamburger [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
            {name = "cheeseburger", label = "Cheese Burger", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "frite", label = "Frite", price = 5, MaxList = 50, Index = 1, GetItem = false},
            {name = "potatoes", label = "Potatoes", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "burgershot",
        society = "society_burgershot",
        point = vector3(1593.276490, 3746.330566, 34.44),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(1594.327270, 3744.952392, 34.43),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "hamburger", label = "Hamburger [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
            {name = "cheeseburger", label = "Cheese Burger", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "frite", label = "Frite", price = 5, MaxList = 50, Index = 1, GetItem = false},
            {name = "potatoes", label = "Potatoes", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "tacos",
        society = "society_tacos",
        point = vector3(419.487976, -1915.189454, 25.48),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(417.428132, -1914.610474, 25.48),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "tacos", label = "Tacos [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
            {name = "frite", label = "Frite", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "koi",
        society = "society_koi",
        point = vector3(-1060.010864, -1462.693482, -0.90),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-1035.060302, -1482.708130, 4.60),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "sushi", label = "Sushi [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
            {name = "riz", label = "Riz (boule de riz)", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "umeshu", label = "Umeshu (alcool japonais)", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "uwucafe",
        society = "society_uwucafe",
        point = vector3(-584.854310, -1060.484620, 22.35),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-583.224244, -1060.407958, 22.35),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "brownie", label = "Brownie [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
            {name = "cookie", label = "Cookie", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "mochi", label = "Mochi", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "cafe", label = "Café", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "the", label = "Thé", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "bahamas",
        society = "society_bahamas",
        point = vector3(-1378.170288, -599.058594, 30.22),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-1380.273682, -600.217774, 30.22),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_champagne", label = "Bouteille de champagne [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "martini", label = "Martini", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "bahamas",
        society = "society_bahamas",
        point = vector3(-1380.853150, -594.916260, 30.22),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-1383.199218, -595.726562, 30.22),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_champagne", label = "Bouteille de champagne [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "martini", label = "Martini", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "tequilala",
        society = "society_tequilala",
        point = vector3(-561.945252, 286.723602, 82.20),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-560.229126, 286.712158, 82.20),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_tequila", label = "Bouteille de tequila [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "margarita", label = "Margarita", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "unicorn",
        society = "society_unicorn",
        point = vector3(129.512894, -1283.806640, 29.275),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(127.817772, -1284.555176, 29.275),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_vodka", label = "Bouteille de vodka [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "rhum", label = "Rhum", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "yellowjack",
        society = "society_yellowjack",
        point = vector3(1984.010742, 3049.660888, 47.25),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(1985.048096, 3051.018310, 47.22),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_whisky", label = "Bouteille de whisky [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "cognac", label = "Cognac", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "henhouse",
        society = "society_henhouse",
        point = vector3(-297.814118, 6262.521484, 31.49),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-298.318024, 6263.722168, 31.49),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.2,
        Produit = {
            {name = "boeuf_cuit", label = "Tomahawk de boeuf [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "americano", label = "Americano", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_woodford", label = "Bouteille de Woodfort", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "nikkibeach",
        society = "society_nikkibeach",
        point = vector3(-1429.753540, -1263.925538, 3.62),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-1431.318970, -1263.656372, 3.55),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotX = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "frozen_margerita", label = "Frozen margerita [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "mojito", label = "Mojito", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "crepe_nutella", label = "Crêpe nutella", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "donut", label = "Donut", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "glace", label = "Glace", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "nikkibeach",
        society = "society_nikkibeach",
        point = vector3(-1428.057496, -1260.942016, 3.60),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-1429.325684, -1260.020020, 3.52),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotX = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "frozen_margerita", label = "Frozen margerita [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "mojito", label = "Mojito", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "crepe_nutella", label = "Crêpe nutella", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "donut", label = "Donut", price = 20, MaxList = 50, Index = 1, GetItem = false},
            {name = "glace", label = "Glace", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "nikkibeach",
        society = "society_nikkibeach",
        point = vector3(-1458.029296, -1232.398316, 3.3),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-1459.829102, -1232.397460, 3.07),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotX = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "frozen_margerita", label = "Frozen margerita [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "mojito", label = "Mojito", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "nikkibeach",
        society = "society_nikkibeach",
        point = vector3(-1559.280274, -1295.098022, 1.71),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-1558.855102, -1296.659668, 1.71),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotX = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "frozen_margerita", label = "Frozen margerita [Spécialité]", price = 20, MaxList = 50, Index = 1, GetItem = true},
			{name = "mojito", label = "Mojito", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "biere", label = "Bière", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 20, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "ltdls",
        society = "society_ltdls",
        point = vector3(-705.903076, -914.525756, 19.22),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-715.681458, -909.397094, 19.22),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "pain", label = "Pain", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "sandwich", label = "Sandwich", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "drill", label = "Câble en acier", price = 150, MaxList = 50, Index = 1, GetItem = false},
			{name = "radio", label = "Radio", price = 750, MaxList = 50, Index = 1, GetItem = false},
			{name = "petit_appat", label = "Petit-appât", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "moyen_appat", label = "Moyen-appât", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "grand_appat", label = "Grand-appât", price = 55, MaxList = 50, Index = 1, GetItem = false},
            {name = "fishingrod", label = "Canne à pêche", price = 85, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "ltddp",
        society = "society_ltddp",
        point = vector3(-1485.708252, -378.383514, 40.17),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-1486.341064, -382.430390, 40.17),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "pain", label = "Pain", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "sandwich", label = "Sandwich", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "drill", label = "Câble en acier", price = 150, MaxList = 50, Index = 1, GetItem = false},
			{name = "radio", label = "Radio", price = 750, MaxList = 50, Index = 1, GetItem = false},
			{name = "petit_appat", label = "Petit-appât", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "moyen_appat", label = "Moyen-appât", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "grand_appat", label = "Grand-appât", price = 55, MaxList = 50, Index = 1, GetItem = false},
            {name = "fishingrod", label = "Canne à pêche", price = 85, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "ltdmp",
        society = "society_ltdmp",
        point = vector3(1165.144166, -323.557220, 69.21),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(1154.547120, -320.178956, 69.21),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "pain", label = "Pain", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "sandwich", label = "Sandwich", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "drill", label = "Câble en acier", price = 150, MaxList = 50, Index = 1, GetItem = false},
			{name = "radio", label = "Radio", price = 750, MaxList = 50, Index = 1, GetItem = false},
			{name = "petit_appat", label = "Petit-appât", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "moyen_appat", label = "Moyen-appât", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "grand_appat", label = "Grand-appât", price = 55, MaxList = 50, Index = 1, GetItem = false},
            {name = "fishingrod", label = "Canne à pêche", price = 85, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "ltdgs",
        society = "society_ltdgs",
        point = vector3(-47.221408, -1758.907958, 29.425),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-51.363792, -1748.524780, 29.425),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "pain", label = "Pain", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "sandwich", label = "Sandwich", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "drill", label = "Câble en acier", price = 150, MaxList = 50, Index = 1, GetItem = false},
			{name = "radio", label = "Radio", price = 750, MaxList = 50, Index = 1, GetItem = false},
			{name = "petit_appat", label = "Petit-appât", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "moyen_appat", label = "Moyen-appât", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "grand_appat", label = "Grand-appât", price = 55, MaxList = 50, Index = 1, GetItem = false},
            {name = "fishingrod", label = "Canne à pêche", price = 85, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "ltdfd",
        society = "society_ltdfd",
        point = vector3(24.266296, -1346.668458, 29.50),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(32.360290, -1343.224854, 29.52),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "pain", label = "Pain", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "sandwich", label = "Sandwich", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "drill", label = "Câble en acier", price = 150, MaxList = 50, Index = 1, GetItem = false},
			{name = "radio", label = "Radio", price = 750, MaxList = 50, Index = 1, GetItem = false},
			{name = "petit_appat", label = "Petit-appât", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "moyen_appat", label = "Moyen-appât", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "grand_appat", label = "Grand-appât", price = 55, MaxList = 50, Index = 1, GetItem = false},
            {name = "fishingrod", label = "Canne à pêche", price = 85, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "ltdcayo",
        society = "society_cayo",
        point = vector3(5127.033204, -5113.662110, 2.22),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(5130.113282, -5121.950196, 2.235),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "paquet_cigare", label = "Paquet de cigare", price = 25, MaxList = 50, Index = 1, GetItem = false},
            {name = "weapon_petrolcan", label = "Bidon d'essence", price = 45, MaxList = 50, Index = 1, GetItem = false},
            {name = "bouteille_eau", label = "Bouteille d'eau", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "pain", label = "Pain", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "sandwich", label = "Sandwich", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "coca", label = "Coca", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "ice_tea", label = "Ice-Tea", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "oasis", label = "Oasis", price = 15, MaxList = 50, Index = 1, GetItem = false},
			{name = "drill", label = "Câble en acier", price = 150, MaxList = 50, Index = 1, GetItem = false},
			{name = "radio", label = "Radio", price = 750, MaxList = 50, Index = 1, GetItem = false},
			{name = "petit_appat", label = "Petit-appât", price = 5, MaxList = 50, Index = 1, GetItem = false},
			{name = "moyen_appat", label = "Moyen-appât", price = 20, MaxList = 50, Index = 1, GetItem = false},
			{name = "grand_appat", label = "Grand-appât", price = 55, MaxList = 50, Index = 1, GetItem = false},
            {name = "fishingrod", label = "Canne à pêche", price = 85, MaxList = 50, Index = 1, GetItem = false},
        }
    },
    {
        job = "lscustomsud",
        society = "society_lscustomsud",
        point = vector3(-352.063140, -131.266022, 39.25),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(-351.571290, -129.662888, 39.25),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "kit_reparation", label = "Kit de réparation", price = 750, MaxList = 50, Index = 1, GetItem = true},
        }
    },
    {
        job = "lscustomnord",
        society = "society_lscustomnord",
        point = vector3(1203.772216, 2646.922608, 37.81),
        text = "Appuyer ~b~[E]~s~ pour ~g~vendre ~s~au ~b~client",
        pointRecette = vector3(1202.522828, 2648.040772, 37.81),
        textRecette = "Appuyer ~b~[E]~s~ pour ~g~voir ~s~nos ~b~produits en vente",
        description = "",
        markerType = 27,
        sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0, rotX = 0.0, rotY = 0.0, rotZ = 0.0, r = 249, g = 130, b = 42, a = 55555,
        distMarker = 10, dist3D = 1.5,
        Produit = {
            {name = "kit_reparation", label = "Kit de réparation", price = 750, MaxList = 50, Index = 1, GetItem = true},
        }
    }
}