menuProps = {
    LimitProps = 20,
    Props = {
        ["vip"] = {
            {Button = "Télévision", Props = "prop_tv_flat_01"},
            {Button = "Enceinte", Props = "prop_portable_hifi_01"},
            {Button = "Petit barbecue", Props = "prop_bbq_4"},
            {Button = "Moyen barbecue", Props = "prop_bbq_5"},
            {Button = "Grand barbecue", Props = "prop_bbq_1"},
            {Button = "Tente", Props = "prop_skid_tent_03"},
            {Button = "Transat", Props = "prop_patio_lounger1"},
            {Button = "Tonnelle", Props = "prop_gazebo_03"},
            {Button = "Petit parasol", Props = "prop_parasol_04"},
            {Button = "Moyen parasol", Props = "prop_parasol_01"},
            {Button = "Grand parasol", Props = "prop_parasol_05"},
            {Button = "Parasol de plage", Props = "prop_beach_parasol_04"},
            {Button = "Canapé usé", Props = "prop_ld_farm_couch01"},
            {Button = "Fauteuil usé", Props = "prop_rub_couch03"},
            {Button = "Lumière bleu", Props = "prop_runlight_b"},
            {Button = "Lumière verte", Props = "prop_runlight_g"},
            {Button = "Lumière rouge", Props = "prop_runlight_r"},
            {Button = "Lumière jaune", Props = "prop_runlight_y"},
            {Button = "Barre de led", Props = "xm_prop_base_tripod_lampc"},
            {Button = "Petit spot", Props = "prop_walllight_ld_01"},
            {Button = "Table squate", Props = "prop_ld_farm_table02"},
            {Button = "Table picnic", Props = "prop_picnictable_01_lod"},
            {Button = "Table en plastique", Props = "prop_table_03b_cs"},
            {Button = "Chaise en plastique", Props = "prop_table_03_chr"},
            {Button = "Chaise de guetteur", Props = "hei_prop_hei_skid_chair"},
            {Button = "Chaise de boss", Props = "ex_prop_offchair_exec_04"},
            {Button = "Barrière en fer", Props = ""},
            {Button = "Banc en bois", Props = "prop_bench_08"},
            {Button = "Feu de camp", Props = "prop_beach_fire"},
            {Button = "Valise de drogue", Props = "hei_prop_hei_drug_case"},
            {Button = "Table de drogue weed", Props = "bkr_prop_weed_table_01a"},
            {Button = "Table de drogue coke", Props = "bkr_prop_coke_table01a"},
            {Button = "Table de drogue crack", Props = "v_ret_ml_tableb"},
            {Button = "Table de drogue meth", Props = "bkr_prop_meth_table01a"},
        },
        ["police"] = {
            {Button = "Plot", Props = "prop_byard_net02"},
            {Button = "Barrière", Props = "prop_barrier_work05"},
            {Button = "Panneau gauche", Props = "prop_sign_road_06q"},
            {Button = "Panneau droite", Props = "prop_sign_road_06r"},
            {Button = "Herse", Props = "p_ld_stinger_s"},
            
        },
        ["sherif"] = {
            {Button = "Plot", Props = "prop_byard_net02"},
            {Button = "Barrière", Props = "prop_barrier_work05"},
            {Button = "Panneau gauche", Props = "prop_sign_road_06q"},
            {Button = "Panneau droite", Props = "prop_sign_road_06r"},
            {Button = "Herse", Props = "p_ld_stinger_s"},
        },
        ["ems"] = {
            {Button = "Plot", Props = "prop_byard_net02"},
            {Button = "Barrière", Props = "prop_barrier_work06a"},
            {Button = "Panneau gauche", Props = "prop_sign_road_06q"},
            {Button = "Panneau droite", Props = "prop_sign_road_06r"},
            {Button = "Chaise roulante", Props = "prop_wheelchair_01"},
            {Button = "Boite réanimation", Props = "sm_prop_smug_crate_s_medical"},
            {Button = "Sac médical", Props = "xm_prop_x17_bag_med_01a"},
        },
        ["lscustomnord"] = {
            {Button = "Plot", Props = "prop_byard_net02"},
            {Button = "Barrière", Props = "prop_tool_sawhorse"},
            {Button = "Caisse à outil", Props = "prop_tool_box_04"},
        },
        ["lscustomsud"] = {
            {Button = "Plot", Props = "prop_byard_net02"},
            {Button = "Barrière", Props = "prop_tool_sawhorse"},
            {Button = "Caisse à outil", Props = "prop_tool_box_04"},
        },
        ["benny"] = {
            {Button = "Plot", Props = "prop_byard_net02"},
            {Button = "Barrière", Props = "prop_tool_sawhorse"},
            {Button = "Caisse à outil", Props = "prop_tool_box_04"},
        },
        ["garage_cayo"] = {
            {Button = "Plot", Props = "prop_byard_net02"},
            {Button = "Barrière", Props = "prop_tool_sawhorse"},
            {Button = "Caisse à outil", Props = "prop_tool_box_04"},
        },
        ["mineur"] = {
            {Button = "Petit spot", Props = "prop_worklight_02a"},
            {Button = "Grand spot", Props = "prop_worklight_03a"},
        },
    }
}