FarmIllegal = {
    Recolte = {
        {
            point = vector3(2224.196, 5576.958, 53.8),
            item = "branche_weed_critical", itemLabel = "Branche de weed", itemReward = 1,
            maxDistMarker = 10, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~branches de weed~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 1,
            speedFarm = 0.0040,
            Button = "Récolte des branches de weed", description = "Recolter des branches de weed"
        },
        
        {
            point = vector3(-1625.356, 4573.196, 43.43296),
            item = "feuille_coca", itemLabel = "Feuille de coca", itemReward = 1,
            maxDistMarker = 10, distMax3D = 4, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ des ~b~feuilles de coca~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 1,
            speedFarm = 0.0040,
            Button = "Récolte des feuilles de coca", description = "Recolter des feuilles de coca"
        },
        {
            point = vector3(1442.848, 6333.156, 23.8996),
            item = "pseudoephedrine", itemLabel = "Pseudoephedrine", itemReward = 1,
            maxDistMarker = 2, distMax3D = 2, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ de la ~b~pseudoéphédrine~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 1,
            speedFarm = 0.0040,
            Button = "Récolte de la pseudoéphédrine", description = "Récolte de la pseudoéphédrine"
        },
        {
            point = vector3(-456.0372, -1671.896, 19.29108),
            item = "phosphore_rouge", itemLabel = "Phosphore rouge", itemReward = 1,
            maxDistMarker = 2, distMax3D = 2, markerType = 1, text = "Appuyer ~b~[E]~s~ pour ~g~récolter~s~ du ~b~phosphore rouge~s~",
            sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 1,
            speedFarm = 0.0040,
            Button = "Récolte du phosphore rouge", description = "Récolte du phosphore rouge"
        },
    },
    Traitement = {
        {
            point = vector3(-116.865, -2509.784, -5.094312),
            itemNeed = "branche_weed_critical", itemNeedLabel = "Branche de weed", itemRemove = 1, itemMini = 1,
            deuxItem = false, troisItem = false, 
            item2Need = "", item2NeedLabel = "", item2Remove = 1, item2Mini = 1,
            item3Need = "", itemNeedLabel = "", item3Remove = 1, item3Mini = 1,
            itemNameReward = "tete_weed_critical", itemRewardLabel = "Tête de weed", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~traiter~s~ des ~b~branches de weed~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 0,
            speedFarm = 0.0040,
            Button = "Traitement des branches de weed", description = "Traiter des branches de weed"
        }, 
        {
            point = vector3(-119.3954, -2513.418, -5.094366),
            itemNeed = "tete_weed_critical", itemNeedLabel = "Tête de weed", itemRemove = 5, itemMini = 5,
            deuxItem = false, troisItem = false, 
            item2Need = "", item2NeedLabel = "", item2Remove = 1, item2Mini = 1,
            item3Need = "", itemNeedLabel = "", item3Remove = 1, item3Mini = 1,
            itemNameReward = "pochon_weed_critical", itemRewardLabel = "Pochon de weed", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre en pochon~s~ les ~b~têtes de weed~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 0,
            speedFarm = 0.0040,
            Button = "Mettre en pochon les têtes de weed", description = "Mettre en pochon les têtes de weed"
        },
        {
            point = vector3(670.8028, -2701.046, -3.041142),
            itemNeed = "feuille_coca", itemNeedLabel = "Feuille de coca", itemRemove = 1, itemMini = 1,
            deuxItem = true, troisItem = false, 
            item2Need = "acide", item2NeedLabel = "Acide", item2Remove = 1, item2Mini = 1,
            item3Need = "", itemNeedLabel = "", item3Remove = 1, item3Mini = 1,
            itemNameReward = "poudre_coke", itemRewardLabel = "Poudre de coke", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~traiter~s~ les ~b~feuilles de coca~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 0,
            speedFarm = 0.0040,
            Button = "Traitement des feuilles de coca", description = "Traitement des feuilles de coca"
        },
        {
            point = vector3(675.8782, -2697.352, -3.041192),
            itemNeed = "poudre_coke", itemNeedLabel = "Poudre de coke", itemRemove = 5, itemMini = 5,
            deuxItem = false, troisItem = false, 
            item2Need = "", item2NeedLabel = "", item2Remove = 1, item2Mini = 1,
            item3Need = "", itemNeedLabel = "", item3Remove = 1, item3Mini = 1,
            itemNameReward = "pochon_coke", itemRewardLabel = "Pochon de coke", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre en pochon~s~ la ~b~poudre de coke~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 0,
            speedFarm = 0.0040,
            Button = "Mettre en pochon la poudre de coke", description = "Mettre en pochon la poudre de coke"
        },
        {
            point = vector3(1391.794, 3605.928, 38.94188),
            itemNeed = "poudre_coke", itemNeedLabel = "Poudre de coke", itemRemove = 5, itemMini = 5,
            deuxItem = false, troisItem = false, 
            item2Need = "", item2NeedLabel = "", item2Remove = 1, item2Mini = 1,
            item3Need = "", itemNeedLabel = "", item3Remove = 1, item3Mini = 1,
            itemNameReward = "crack", itemRewardLabel = "Crack", itemReward = 5, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~traiter~s~ la ~b~poudre de coke ~s~en ~b~crack",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 0,
            speedFarm = 0.0040,
            Button = "Traitement du crack", description = "Traitement du crack"
        },
        {
            point = vector3(1397.086, 3605.3, 38.94194),
            itemNeed = "crack", itemNeedLabel = "Crack", itemRemove = 5, itemMini = 5,
            deuxItem = false, troisItem = false, 
            item2Need = "", item2NeedLabel = "", item2Remove = 1, item2Mini = 1,
            item3Need = "", itemNeedLabel = "", item3Remove = 1, item3Mini = 1,
            itemNameReward = "pochon_crack", itemRewardLabel = "Pochon de crack", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre en pochon~s~ le ~b~crack~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 0,
            speedFarm = 0.0040,
            Button = "Mettre en pochon le crack", description = "Mettre en pochon le crack"
        },
        {
            point = vector3(1391.776, 2172.286, 87.72282),
            itemNeed = "acide", itemNeedLabel = "Acide", itemRemove = 1, itemMini = 1,
            deuxItem = false, troisItem = true, 
            item2Need = "phosphore_rouge", item2NeedLabel = "Phosphore rouge", item2Remove = 1, item2Mini = 1,
            item3Need = "pseudoephedrine", itemNeedLabel = "Pseudoéphédrine", item3Remove = 1, item3Mini = 1,
            itemNameReward = "crystal_meth", itemRewardLabel = "Crystal de meth", itemReward = 5, 
            maxDistMarker = 5, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~traiter~s~ des ~b~crytaux de meth~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 0,
            speedFarm = 0.0040,
            Button = "Traitement de crystal de meth", description = "Traitement de crystal de meth"
        },
        {
            point = vector3(1382.748, 2167.466, 87.2427),
            itemNeed = "crystal_meth", itemNeedLabel = "Crystal de meth", itemRemove = 5, itemMini = 5,
            deuxItem = false, troisItem = false, 
            item2Need = "", item2NeedLabel = "", item2Remove = 1, item2Mini = 1,
            item3Need = "", itemNeedLabel = "", item3Remove = 1, item3Mini = 1,
            itemNameReward = "pochon_meth", itemRewardLabel = "Pochon de meth", itemReward = 1, 
            maxDistMarker = 20, distMax3D = 2, markerType = 27, text = "Appuyer ~b~[E]~s~ pour ~g~mettre en pochon~s~ le ~b~crystal de meth~s~",
            sizeX = 0.5, sizeY = 0.5,  sizeZ = 1.0,
            rotX = 0.0, rotY = 0.0, rotX = 0.0, 
            r = 249, g = 130, b = 42, a = 55555,
            minimumCops = 0,
            speedFarm = 0.0040,
            Button = "Mettre en pochon le crystal de meth", description = "Mettre en pochon le crystal de meth"
        },
    }
}