ShopIllegal = {
    {
        shop = "Braqueur",
        WeaponIllimited = true,
        point = vector3(2327.653320, 2570.027100, 47.676704),
        text = "Appuyer ~b~[E]~s~ pour ~g~parler ~s~au ~b~Gangster",
        separator = "↓ ~b~Vendeur d'objets illégaux~s~ ↓",
        markerType = 6,
        sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
        rotX = -90.0, rotY = -90.0, rotX = -90.0, 
        r= 255, g = 255, b = 255, a = 55555,
        distMarker = 10,
        dist3D = 1.5,
        maxWeapon = 3,
        GangAutorized = {"ballas", "vagos", "f4l", "bloods", "marabunta", "oneil", "bmf", "lostmc", "madrazo"},
        Boss = false,
        Weapon = {
            {label = "Pavé", name = "WEAPON_SNOWBALL", price = 150, maxList = 3, Index = 1},
			{label = "Menotte", name = "menotte", price = 1500, maxList = 50, Index = 1},
            {label = "Téléphone de bicrave", name = "telephone_bicrave", price = 1850, maxList = 50, Index = 1},
			{label = "Perceuse", name = "drill", price = 4500, maxList = 50, Index = 1},
			{label = "Casse vitre", name = "casse_vitre", price = 5000, maxList = 50, Index = 1},
            {label = "Grenade fumigène", name = "WEAPON_SMOKE", price = 5250, maxList = 50, Index = 1},
			{label = "Molotov", name = "WEAPON_MOLOTOV", price = 6000, maxList = 50, Index = 1},
			{label = "Clé piratage", name = "cle_piratage", price = 6500, maxList = 50, Index = 1}
        }
    },
    {
        shop = "Gangster",
        WeaponIllimited = false,
        point = vector3(-1164.514648, -477.018768, 50.261948),
        text = "Appuyer ~b~[E]~s~ pour ~g~parler ~s~au ~b~Gangster",
        separator = "↓ ~b~Vendeur d'arme blanche~s~ ↓",
        markerType = 6,
        sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
        rotX = -90.0, rotY = -90.0, rotX = -90.0, 
        r= 255, g = 255, b = 255, a = 55555,
        distMarker = 10,
        dist3D = 1.5,
        maxWeapon = 3,
        GangAutorized = {"ballas", "vagos", "f4l", "bloods", "marabunta", "oneil", "bmf", "lostmc", "madrazo"},
        Boss = true,
        Weapon = {
            {label = "Marteau", name = "WEAPON_HAMMER", price = 1850, maxList = 3, Index = 1},
		    {label = "Bouteille cassé", name = "WEAPON_BOTTLE", price = 1700, maxList = 3, Index = 1},
		    {label = "Poing américain", name = "WEAPON_KNUKLE", price = 1700, maxList = 3, Index = 1},
		    {label = "Couteau", name = "WEAPON_KNIFE", price = 2200, maxList = 3, Index = 1},
		    {label = "Queue de billard", name = "WEAPON_POOLCUE", price = 2600, maxList = 3, Index = 1},
		    {label = "Batte de baseball", name = "WEAPON_BAT", price = 2200, maxList = 3, Index = 1},
		    {label = "Clé anglaise", name = "WEAPON_WRENCH", price =3000, maxList = 3, Index = 1},
		    {label = "Pied de biche", name = "WEAPON_CROWBAR", price = 3000, maxList = 3, Index = 1},
		    {label = "Machette", name = "WEAPON_MACHETE", price = 3000, maxList = 3, Index = 1},
		    {label = "Cran d'arrêt", name = "WEAPON_SWITCHBLADE", price = 3500, maxList = 3, Index = 1},
		    {label = "Hachette", name = "WEAPON_HATCHET", price = 3500, maxList = 3, Index = 1},
		    {label = "Hache de guerre", name = "WEAPON_BATTLEAXE", price = 4500, maxList = 3, Index = 1},
            {label = "Katana (VIP)", name = "", price = 2000, maxList = 3, Index = 1, vip = true},
		    {label = "Dague Antique (VIP)", name = "WEAPON_DAGGER", price = 2000, maxList = 3, Index = 1, vip = true},
        }
    },
    {
        shop = "Bandit",
        WeaponIllimited = false,
        point = vector3(706.947448, -695.887512, 32.754246),
        text = "Appuyer ~b~[E]~s~ pour ~g~parler ~s~au ~b~Bandit",
        separator = "↓ ~b~Vendeur d'armes à feu~s~ ↓",
        markerType = 6,
        sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
        rotX = -90.0, rotY = -90.0, rotX = -90.0, 
        r= 255, g = 255, b = 255, a = 55555,
        distMarker = 10,
        dist3D = 1.5,
        maxWeapon = 3,
        GangAutorized = {"ballas", "vagos", "f4l", "bloods", "marabunta", "oneil", "bmf", "lostmc", "madrazo"},
        Boss = false,
        Weapon = {
			{label = "Pétoire", name = "WEAPON_SNSPISTOL", price = 35000, maxList = 3, Index = 1},
            {label = "Beretta", name = "WEAPON_PISTOL", price = 75000, maxList = 3, Index = 1},
			{label = "Pïstolet lourd", name = "WEAPON_HEAVYPISTOL", price = 95000, maxList = 3, Index = 1},
			{label = "Pistolet Cal.50", name = "weapon_pistol50", price = 115000, maxList = 3, Index = 1},
			{label = "Boite .45ACP", name = "boite_mun_pistol", price = 2000, maxList = 3, Index = 1}
        }
    },
    {
        shop = "Sicario",
        WeaponIllimited = false,
        point = vector3(3612.895264, 5023.893554, 12.345372),
        text = "Appuyer ~b~[E]~s~ pour ~g~parler ~s~au ~b~Sicario",
        separator = "↓ ~b~Vendeur de mitraillettes~s~ ↓",
        markerType = 6,
        sizeX = 0.0, sizeY = 0.0,  sizeZ = 0.0,
        rotX = -90.0, rotY = -90.0, rotX = -90.0, 
        r= 255, g = 255, b = 255, a = 55555,
        distMarker = 10,
        dist3D = 1.5,
        maxWeapon = 3,
        GangAutorized = {"bandadiaz"},
        Boss = false,
        Weapon = {
            {label = "Mini-Uzi", name = "WEAPON_MICROSMG", price = 465000, maxList = 3, Index = 1},
            {label = "Scorpion", name = "WEAPON_MINISMG", price = 535000, maxList = 3, Index = 1},
			{label = "Tech-9", name = "WEAPON_MACHINEPISTOL", price = 685000, maxList = 3, Index = 1},
			{label = "Boite 9mm", name = "boite_mun_mitraillette", price = 3000, maxList = 3, Index = 1}
        }
    }
}