Administration = {}
weightSysteme = true
Administration.posUnJail = vec3(234.457626, -888.411194, 30.491730)

PermsCommannd = {"admin", "superadmin"}

Administration.TablegestionGrade = {
    {label = "Menu Admin", name = "menuadmin", status = false},
    {label = "Afficher nombre report", name = "shownvbrreport", status = false},
    {label = "Menu Report", name = "menureport", status = false},
    {label = "Voir les reports", name = "showreport", status = false},
    {label = "Menu personnel", name = "menupersonnel", status = false},
    {label = "Menu Météo", name = "meteo", status = false},
    {label = "Menu Joueur", name = "menujoueur", status = false},
    {label = "Info joueur", name = "infojoueur", status = false},
    {label = "Menu Vehicule", name = "menuvehicle", status = false},
    {label = "Menu Serveur", name = "menuserveur", status = false},
    {label = "Menu Options", name = "menuoptions", status = false},
    {label = "Menu ped", name = "menuped", status = false},
    {label = "Liste des joueurs", name = "listeplayer", status = false},
    {label = "Liste des joueurs hors ligne", name = "listeplayeroffline", status = false},
    {label = "Vehicule options", name = "vehicleoption", status = false},
    {label = "Spawn Vehicule", name = "spawnvehicule", status = false},
    {label = "Menu mapping", name = "mapping", status = false},
    {label = "Gestion du serveur", name = "gestionserveur", status = false},
    {label = "Crée un item", name = "createitem", status = false},
    {label = "Noclip", name = "noclip", status = false},
    {label = "Remettre la personne ou elle était", name = "remettreplayer", status = false},
    {label = "Tags Joueur", name = "tagsjoueur", status = false},
    {label = "Blips Joueur", name = "blipsjoueur", status = false},
    {label = "GodMode", name = "godmode", status = false},
    {label = "TP marker", name = "tpmarker", status = false},
    {label = "Setjob", name = "sesetjob", status = false},
    {label = "Action soins", name = "actionsoins", status = false},
    {label = "give de l'argent", name = "givemoney", status = false},
    {label = "Give item", name = "giveitem", status = false},
    {label = "Revive", name = "revive", status = false},
    {label = "Heal", name = "heal", status = false},
    {label = "Invincible", name = "invincible", status = false},
    {label = "Spectacte",  name = "spectacte", status = false},
    {label = "Info Serveur", name = "infoserveur", status = false},
    {label = "TP joueur", name = "tpjoueur", status = false},
    {label = "Action sanction", name = "sanction", status = false},
    {label = "Envoyer un message", name = "sendmessage", status = false},
    {label = "Liste Warn", name = "listewarn", status = false},
    {label = "Annonce serveur", name = "annonceserveur", status = false},
    {label = "Freeze", name = "freeze", status = false},
}

WipeLicense = {
    {label = "Code de la route", Type = "dmv"},
    {label = "Permis voiture", Type = "drive"},
    {label = "Permis moto", Type = "drive_bike"},
    {label = "Permis camion", Type = "drive_truck"},
    {label = "Permis d'arme", Type = "weapon"},
    
}

Administration.Temps = {
    {command = "morning", label = "Matin"},
    {command = "noon", label = "Midi", },
    {command = "evening" , label = "Soirée"},
    {command = "night", label = "Soir"},
    {command = "blackout", label =  "Blackout"},
}




noclip = {
    controls = {
        openKey = 289,
        goUp = 85,
        goDown = 48,
        turnLeft = 34,
        turnRight = 35,
        goForward = 32,
        goBackward = 33,
        changeSpeed = 21,
    },

    speeds = {
        { label = "Very Slow", speed = 0},
        { label = "Slow", speed = 0.5},
        { label = "Normal", speed = 2},
        { label = "Fast", speed = 4},
        { label = "Very Fast", speed = 6},
        { label = "Extremely Fast", speed = 10},
        { label = "Extremely Fast v2.0", speed = 20},
        { label = "Max Speed", speed = 25},
    },

    offsets = {
        y = 0.5,
        z = 0.2, 
        h = 3, 
    },

    bgR = 0,
    bgG = 0, 
    bgB = 0,
    bgA = 80,
}

Administration.Meteo = {
    {command = "weather EXTRASUNNY", label = "EXTRA ENSOLEILLÉ"},
    {command = "weather CLEAR", label = "CLAIR"},
    {command = "weather NEUTRAL", label = "NEUTRE"},
    {command = "weather SMOG", label = "SMOG"},
    {command = "weather FOGGY", label = "BRUMEUX"},
    {command = "weather OVERCAST", label = "COUVERT"},
    {command = "weather CLOUDS", label = "DES NUAGES"},
    {command = "weather CLEARING", label = "CLAIRIÈRE"},
    {command = "weather RAIN", label = "PLUIE"},
    {command = "weather THUNDER", label = "TONNERRE"},
    {command = "weather SNOW", label = "NEIGE"},
    {command = "weather BLIZZARD", label = "TEMPÊTE DE NEIGE"},
    {command = "weather SNOWLIGHT", label = "CLAIR DE NEIGE"},
    {command = "weather XMAS", label = "NOËL"},
    {command = "weather HALLOWEEN", label = "HALLOWEEN"},
}

Administration.PosMapping = {
    {label = "BurgerShot", coords = vec3(1582.680786, 3749.945312, 34.429088)},
    {label = "Vigneron", coords = vec3(-1890.582398, 2042.776856, 140.960312)},
    {label = "PDP RockFord Hills", coords = vec3(-369.831298, -354.153992, 31.654748)},
    {label = "PDP Academy", coords = vec3(829.455384, -1290.823608, 28.244920)},
    {label = "LSSD Paleto", coords = vec3(-445.056214, 6011.553222, 32.288678)},
    {label = "LSSD SandyShort", coords = vec3(1828.027222, 3679.921630, 34.326134)},
    {label = "EMS SandyShort", coords = vec3(1768.550170, 3637.234130, 34.852570)},
    {label = "EMS Paleto", coords = vec3(-60.350128, 6521.419922, 31.462634)},
    {label = "EMS Sud", coords = vec3(-1854.082886, -339.676728, 49.441498)},
    {label = "Bahamas", coords = vec3(-1385.775878, -588.856750, 30.214034)},
    {label = "Unicorn", coords = vec3(128.964996, -1296.347412, 29.269328)},
    {label = "Benny's", coords = vec3(-209.863938, -1324.064576, 31.300466)},
    {label = "LsCustomSud", coords = vec3(-336.909516, -113.098176, 38.991276)},
    {label = "LsCustomNord", coords = vec3(1201.262330, 2651.819824, 37.806674)},
    {label = "Hen House", coords = vec3(-302.514740, 6259.402344, 31.482086)},
    {label = "YellowJack", coords = vec3(1983.413696, 3052.820800, 50.502320)},
    {label = "Nikki Beach", coords = vec3(-1421.596070, -1234.338746, 4.323588)},
    {label = "Auto Tamponeuse", coords = vec3(-1782.575806, -1077.405884, 13.418930)},
    {label = "Apple Store", coords = vec3(156.518722, -213.850784, 54.251308)},
    {label = "Pacific Sud", coords = vec3(248.172134, 225.204896, 106.282242)},
    {label = "Pacific Nord", coords = vec3(-109.331292, 6463.788574, 31.639492)},
    {label = "Magasin de masque", coords = vec3(-1120.648438, -1439.286132, 5.228328)},
    {label = "Port Commercial", coords = vec3(4992.294922, -5175.704590, 2.500328)},
    {label = "Horny's Burger", coords = vec3(1241.736816, -362.824096, 69.082062)},
    {label = "Tacos", coords = vec3(415.765716, -1911.897828, 25.471214)},
    {label = "KoÏ", coords = vec3(-1039.755494, -1476.156006, 5.579568)},
    {label = "Concessionnaire Auto", coords = vec3(-45.346562, -1102.221070, 27.313716)},
    {label = "Concessionnaire Moto", coords = vec3(984.612976, -126.165748, 74.061226)},
    {label = "Concessionnaire Bateau", coords = vec3(-808.087402, -1363.261230, 5.178346)},
    {label = "Tabac", coords = vec3(2903.069824, 4404.346680, 50.285580)},
    {label = "Mineur", coords = vec3(2523.899170, 4120.880372, 38.918174)},
    {label = "Prison", coords = vec3(1840.503418, 2586.173096, 46.014354)},
    {label = "Maison Walid", coords = vec3(-227.255402, 6451.257812, 31.375064)},
    {label = "Gouvernement", coords = vec3(-549.272034, -198.142486, 38.226948)},
    {label = "QG Vagos", coords = vec3(327.383300, -1991.691406, 24.207754)},
    {label = "QG Ballas", coords = vec3(-5.457112, -1825.211548, 29.152662)},
    {label = "QG Marabunta", coords = vec3(1256.348388, -1568.688476, 58.351596)},
    {label = "QG F4l", coords = vec3(-155.377044, -1618.728516, 33.649376)},
    {label = "QG Nudiste", coords = vec3(-1110.001954, 4939.901368, 218.358840)},
    {label = "Weazel Newz", coords = vec3(-595.907348, -929.859130, 23.875282)},
    {label = "UwU Café", coords = vec3(-580.976014, -1066.682250, 22.339532)},
    {label = "Laboratoire Weed", coords = vec3(-113.659904, -2496.117676, -2.493576)},
    {label = "Laboratoire Coke", coords = vec3(659.748718, -2702.262208, -0.440388)},
    {label = "Laboratoire Meth", coords = vec3(1398.973388, 2171.020508, 89.843452)},
}


Administration.ListPed = {
    {name = "a_c_cat_01", label = "Chat", Type = "Animal"},
    {name = "a_c_chimp", label = "Singe", Type = "Animal"},
    {name = "a_c_chickenhawk", label = "Aigle", Type = "Animal"},
    {name = "a_c_chop", label = "Chop", Type = "Animal"},
    {name = "a_c_cormorant", label = "Oiseau", Type = "Animal"},
    {name = "a_c_cow", label = "Vache", Type = "Animal"},
    {name = "a_c_coyote", label = "Coyote", Type = "Animal"},
    {name = "a_c_crow", label = "Corbeau", Type = "Animal"},
    {name = "a_c_deer", label = "Biche", Type = "Animal"},
    {name = "a_c_dolphin", label = "Dophin", Type = "Animal"},
    {name = "a_c_fish", label = "Poisson", Type = "Animal"},
    {name = "a_c_hen", label = "Poule", Type = "Animal"},
    {name = "a_c_husky", label = "Husky", Type = "Animal"},
    {name = "a_c_killerwhale", label = "Orque", Type = "Animal"},
    {name = "a_c_mtlion", label = "Lion", Type = "Animal"},
    {name = "a_c_pigeon", label = "Pigeon", Type = "Animal"},
    {name = "a_c_poodle", label = "Caniche", Type = "Animal"},
    {name = "a_c_pug", label = "Pug", Type = "Animal"},
    {name = "a_c_rabbit_01", label = "Lapin", Type = "Animal"},
    {name = "a_c_rat", label = "Rat", Type = "Animal"},
    {name = "a_c_retriever", label = "Retriever", Type = "Animal"},
    {name = "a_c_rhesus", label = "Singe", Type = "Animal"},
    {name = "a_c_rottweiler", label = "Rottweiler", Type = "Animal"},
    {name = "a_c_seagull", label = "Mouette", Type = "Animal"},
    {name = "a_c_shepherd", label = "Berger", Type = "Animal"},
    {name = "a_c_westy", label = "Westy", Type = "Animal"},
    {name = "csb_ramp_mex", label = "M13", Type = "Gang"},
    {name = "g_m_importexport_01", label = "Importexport", Type = "Gang"},
    {name = "g_m_m_armboss_01", label = "Armboss", Type = "Gang"},
    {name = "g_m_m_armgoon_01", label = "Armgoon", Type = "Gang"},
    {name = "g_m_m_armlieut_01", label = "Armlieut", Type = "Gang"},
    {name = "g_m_m_chemwork_01", label = "Chimie / Fabricant", Type = "Gang"},
    {name = "g_m_m_chicold_01", label = "Cagoule", Type = "Gang"},
    {name = "g_m_m_korboss_01", label = "Korboss", Type = "Gang"},
    {name = "g_m_m_mexboss_01", label = "Mexboss", Type = "Gang"},
    {name = "g_m_m_mexboss_02", label = "Mexbo", Type = "Gang"},
    {name = "g_m_y_armgoon_02", label = "Armgoon", Type = "Gang"},
    {name = "g_m_y_azteca_01", label = "Aztecaz", Type = "Gang"},
    {name = "ig_ballasog", label = "BigBallas", Type = "Gang"},
    {name = "g_m_y_ballaeast_01", label = "Ballas V1", Type = "Gang"},
    {name = "g_m_y_ballaorig_01", label = "Ballas V2", Type = "Gang"},
    {name = "g_m_y_ballasout_01", label = "Ballas V3", Type = "Gang"},
    {name = "g_m_y_famca_0", label = "F4L V1", Type = "Gang"},
    {name = "csb_ramp_gang", label = "F4L V2", Type = "Gang"},
    {name = "g_m_y_famdnf_01", label = "F4L V3", Type = "Gang"},
    {name = "g_m_y_famfor_01", label = "Famfor", Type = "Gang"},
    {name = "ig_hao", label = "Hao", Type = "Gang"},
    {name = "g_m_m_chigoon_01", label = "Chinois V1", Type = "Gang"},
    {name = "g_m_y_korean_01", label = "Chinois V2", Type = "Gang"},
    {name = "g_m_y_korean_02", label = "Chinois V3", Type = "Gang"},
    {name = "g_m_y_korlieut_01", label = "Chinois V4", Type = "Gang"},
    {name = "s_m_y_dealer_01", label = "Dealer", Type = "Gang"},
    {name = "ig_claypain", label = "Bloods", Type = "Gang"},
    {name = "g_m_y_lost_02", label = "Lost V1", Type = "Gang"},
    {name = "g_m_y_lost_03", label = "Lost V2", Type = "Gang"},
    {name = "g_m_y_mexgang_01", label = "Madrazo", Type = "Gang"},
    {name = "g_m_y_mexgoon_01", label = "Vagos V1", Type = "Gang"},
    {name = "g_m_y_mexgoon_02", label = "Vagos V2", Type = "Gang"},
    {name = "g_m_y_mexgoon_03", label = "Mexician", Type = "Gang"},
    {name = "g_m_y_salvaboss_01", label = "Mara V1", Type = "Gang"},
    {name = "g_m_y_salvagoon_01", label = "Mara V2", Type = "Gang"},
    {name = "g_m_y_salvagoon_02", label = "Salvador", Type = "Gang"},
    {name = "s_m_y_prismuscl_01", label = "Prisonnier V1", Type = "Gang"},
    {name = "s_m_y_prisoner_01", label = "Prisonnier V2", Type = "Gang"},
    {name = "ig_rashcosvki", label = "Prisonnier V3", Type = "Gang"},
    {name = "u_m_y_prisoner_01", label = "Prisonnier V4", Type = "Gang"},
    {name = "ig_lamardavis", label = "Lamar", Type = "Gang"},
    {name = "ig_ortega", label = "Ortega", Type = "Gang"},
    {name = "g_f_y_ballas_01", label = "Ballas Fille", Type = "Gang"},
    {name = "g_f_y_families_01", label = "F4L Fille", Type = "Gang"},
    {name = "g_f_y_lost_01", label = "Lost Fille", Type = "Gang"},
    {name = "g_f_y_vagos_01", label = "Vagos Fille", Type = "Gang"},
    {name = "g_f_importexport_01", label = "Importexport01", Type = "Gang"},
    {name = "csb_trafficwarden", label = "Stagiaire LSPD", Type = "Job"},
    {name = "s_m_y_cop_01", label = "LSPD", Type = "Job"},
    {name = "s_f_y_cop_01", label = "LSPD Fille", Type = "Job"},
    {name = "s_m_y_swat_01", label = "SWAT", Type = "Job"},
    {name = "cs_bankman", label = "Bankier", Type = "Job"},
    {name = "cs_barry", label = "Barman", Type = "Job"},
    {name = "cs_casey", label = "Grupp 6", Type = "Job"},
    {name = "cs_floyd", label = "Eboueur", Type = "Job"},
    {name = "cs_karen_daniel", label = "Inspectrice", Type = "Job"},
    {name = "s_m_m_ciasec_01", label = "Inspecteur ", Type = "Job"},
    {name = "cs_mrs_thornhill", label = "Maitresse ", Type = "Job"},
    {name = "cs_prolsec_02", label = "Sheriff V1", Type = "Job"},
    {name = "csb_cop", label = "Sheriff V2", Type = "Job"},
    {name = "csb_prol", label = "Sheriff V3", Type = "Job"},
    {name = "s_f_y_ranger_01", label = "Sheriff Fille", Type = "Job"},
    {name = "s_f_y_sheriff_01", label = "Sheriff Fille V2", Type = "Job"},
    {name = "csb_chef", label = "Tacos", Type = "Job"},
    {name = "csb_mweather", label = "Meryweather", Type = "Job"},
    {name = "csb_ramp_marin", label = "Armee", Type = "Job"},
    {name = "s_m_y_blackops_02", label = "Armee V2", Type = "Job"},
    {name = "s_m_m_marine_01", label = "General", Type = "Job"},
    {name = "s_m_m_marine_02", label = "Caporal", Type = "Job"},
    {name = "csb_vincent", label = "Agent secu", Type = "Job"},
    {name = "mp_g_m_pros_01", label = "Agent secu V2", Type = "Job"},
    {name = "s_m_m_bouncer_01", label = "Agent de secu V3", Type = "Job"},
    {name = "mp_m_boatstaff_01", label = "Chauffeur bateau", Type = "Job"},
    {name = "mp_m_fibsec_01", label = "FIB", Type = "Job"},
    {name = "mp_m_securoguard_01", label = "Securo", Type = "Job"},
    {name = "mp_m_waremech_01", label = "Mecano", Type = "Job"},
    {name = "s_m_m_ccrew_01", label = "Mecano V2", Type = "Job"},
    {name = "mp_m_weapexp_01", label = "Armurerie", Type = "Job"},
    {name = "s_f_m_maid_01", label = "Dame de menage", Type = "Job"},
    {name = "s_m_m_doctor_01", label = "EMS", Type = "Job"},
    {name = "s_m_m_paramedic_01", label = "EMS2", Type = "Job"},
    {name = "s_m_y_autopsy_01", label = "EMS3", Type = "Job"},
    {name = "s_f_y_scrubs_01", label = "EMS Fille", Type = "Job"},
    {name = "s_m_m_gaffer_01", label = "Peintre", Type = "Job"},
    {name = "s_m_m_highsec_01", label = "Garde du corps", Type = "Job"},
    {name = "s_f_y_casino_01", label = "Casino Fille", Type = "Job"},
    {name = "u_m_m_streetart_01", label = "Humain Singe", Type = "Homme"},
    {name = "a_m_m_afriamer_01", label = "Afriamer", Type = "Homme"},
    {name = "a_m_m_beach_01", label = "Beach", Type = "Homme"},
    {name = "a_m_m_beach_02", label = "Beach02", Type = "Homme"},
    {name = "a_m_m_bevhills_01", label = "Bevhills", Type = "Homme"},
    {name = "a_m_m_bevhills_02", label = "Bevhills02", Type = "Homme"},
    {name = "a_m_m_business_01", label = "Business", Type = "Homme"},
    {name = "a_m_m_eastsa_01", label = "Eastsa", Type = "Homme"},
    {name = "a_m_m_eastsa_02", label = "Eastsa02", Type = "Homme"},
    {name = "a_m_m_farmer_01", label = "Farmer", Type = "Homme"},
    {name = "a_m_m_fatlatin_01", label = "Fatlatin", Type = "Homme"},
    {name = "a_m_m_genfat_01", label = "Genfat", Type = "Homme"},
    {name = "a_m_m_genfat_02", label = "Genfat", Type = "Homme"},
    {name = "a_m_m_golfer_01", label = "Golfer", Type = "Homme"},
    {name = "a_m_m_hasjew_01", label = "Hasjew", Type = "Homme"},
    {name = "a_m_m_hillbilly_01", label = "Hillbilly", Type = "Homme"},
    {name = "a_m_m_hillbilly_02", label = "Hillbilly_02", Type = "Homme"},
    {name = "a_m_m_indian_01", label = "Indian", Type = "Homme"},
    {name = "a_m_m_ktown_01", label = "Ktown", Type = "Homme"},
    {name = "a_m_m_malibu_01", label = "Malibu", Type = "Homme"},
    {name = "a_m_m_mexcntry_01", label = "Mexcntry", Type = "Homme"},
    {name = "a_m_m_mexlabor_01", label = "Mexlabor", Type = "Homme"},
    {name = "a_m_m_og_boss_01", label = "Og_boss", Type = "Homme"},
    {name = "a_m_m_paparazzi_01", label = "Paparazzi", Type = "Homme"},
    {name = "a_m_m_polynesian_01", label = "Polynesian", Type = "Homme"},
    {name = "a_m_m_prolhost_01", label = "Prolhost", Type = "Homme"},
    {name = "a_m_m_rurmeth_01", label = "Rurmeth", Type = "Homme"},
    {name = "a_m_m_salton_01", label = "Salton", Type = "Homme"},
    {name = "a_m_m_salton_02", label = "Salton_02", Type = "Homme"},
    {name = "a_m_m_salton_03", label = "Salton_03", Type = "Homme"},
    {name = "a_m_m_salton_04", label = "Salton_04", Type = "Homme"},
    {name = "a_m_m_skater_01", label = "Skater", Type = "Homme"},
    {name = "a_m_m_skidrow_01", label = "Skidrow", Type = "Homme"},
    {name = "a_m_m_socenlat_01", label = "Socenlat", Type = "Homme"},
    {name = "a_m_m_soucent_01", label = "Soucent", Type = "Homme"},
    {name = "a_m_m_soucent_02", label = "Soucent_02", Type = "Homme"},
    {name = "a_m_m_soucent_03", label = "Soucent_03", Type = "Homme"},
    {name = "a_m_m_soucent_04", label = "Soucent_04", Type = "Homme"},
    {name = "a_m_m_stlat_02", label = "Stlat", Type = "Homme"},
    {name = "a_m_m_tennis_01", label = "Tennis", Type = "Homme"},
    {name = "a_m_m_tourist_01", label = "Tourist", Type = "Homme"},
    {name = "a_m_m_tramp_01", label = "Tramp_01", Type = "Homme"},
    {name = "a_m_m_trampbeac_01", label = "Trampbeac_01", Type = "Homme"},
    {name = "a_m_o_acult_02", label = "Acult", Type = "Homme"},
    {name = "a_m_o_beach_01", label = "Beach_01", Type = "Homme"},
    {name = "a_m_o_genstreet_01", label = "Genstreet_01", Type = "Homme"},
    {name = "a_m_o_ktown_01", label = "Ktown_01", Type = "Homme"},
    {name = "a_m_o_salton_01", label = "Salton_01", Type = "Homme"},
    {name = "a_m_o_soucent_01", label = "Soucent_01", Type = "Homme"},
    {name = "a_m_o_soucent_02", label = "Clochard", Type = "Homme"},
    {name = "a_m_o_soucent_03", label = "Clochard 2", Type = "Homme"},
    {name = "a_m_o_tramp_01", label = "Clochard 3", Type = "Homme"},
    {name = "a_m_y_acult_01", label = "Clochard 4", Type = "Homme"},
    {name = "a_m_y_acult_02", label = "Clochard 5", Type = "Homme"},
    {name = "a_m_y_beach_01", label = "Beach_01", Type = "Homme"},
    {name = "a_m_y_beach_02", label = "Beach_02", Type = "Homme"},
    {name = "a_m_y_beachvesp_01", label = "Beachvesp_01", Type = "Homme"},
    {name = "a_m_y_beachvesp_02", label = "Beachvesp_02", Type = "Homme"},
    {name = "a_m_y_bevhills_01", label = "Bevhills_01", Type = "Homme"},
    {name = "a_m_y_bevhills_02", label = "Bevhills_02", Type = "Homme"},
    {name = "a_m_y_breakdance_01", label = "Breakdance_01", Type = "Homme"},
    {name = "a_m_y_busicas_01", label = "Busicas_01", Type = "Homme"},
    {name = "a_m_y_business_01", label = "Business_01", Type = "Homme"},
    {name = "a_m_y_business_02", label = "Business_02", Type = "Homme"},
    {name = "a_m_y_business_03", label = "Business_03", Type = "Homme"},
    {name = "a_m_y_clubcust_01", label = "Clubcust_01", Type = "Homme"},
    {name = "a_m_y_cyclist_01", label = "Cyclist_01", Type = "Homme"},
    {name = "a_m_y_dhill_01", label = "Dhill_01", Type = "Homme"},
    {name = "a_m_y_downtown_01", label = "Downtown_01", Type = "Homme"},
    {name = "a_m_y_eastsa_01", label = "Eastsa_01", Type = "Homme"},
    {name = "a_m_y_eastsa_02", label = "Eastsa_02", Type = "Homme"},
    {name = "a_m_y_epsilon_01", label = "Epsilon_01", Type = "Homme"},
    {name = "a_m_y_epsilon_02", label = "Epsilon_02", Type = "Homme"},
    {name = "a_m_y_gay_01", label = "Gay_01", Type = "Homme"},
    {name = "a_m_y_gay_02", label = "Gay_02", Type = "Homme"},
    {name = "a_m_y_genstreet_01", label = "Genstreet_01", Type = "Homme"},
    {name = "a_m_y_genstreet_02", label = "Genstreet_02", Type = "Homme"},
    {name = "a_m_y_golfer_01", label = "Glfer_01", Type = "Homme"},
    {name = "a_m_y_hasjew_01", label = "Hasjew_01", Type = "Homme"},
    {name = "a_m_y_hiker_01", label = "Hiker_01", Type = "Homme"},
    {name = "a_m_y_hippy_01", label = "Hippy_01", Type = "Homme"},
    {name = "a_m_y_hippy_01", label = "Hippy_01", Type = "Homme"},
    {name = "a_m_y_hipster_02", label = "Hipster_02", Type = "Homme"},
    {name = "a_m_y_hipster_03", label = "Hipster_03", Type = "Homme"},
    {name = "a_m_y_indian_01", label = "Indian_01", Type = "Homme"},
    {name = "a_m_y_jetski_01", label = "Jetski_01", Type = "Homme"},
    {name = "a_m_y_juggalo_01", label = "Juggalo_01", Type = "Homme"},
    {name = "a_m_y_ktown_01", label = "Ktown_01", Type = "Homme"},
    {name = "a_m_y_ktown_02", label = "Ktown_02", Type = "Homme"},
    {name = "a_m_y_latino_01", label = "Latino_01", Type = "Homme"},
    {name = "a_m_y_methhead_01", label = "Methhead_01", Type = "Homme"},
    {name = "a_m_y_mexthug_01", label = "Mexthug_01", Type = "Homme"},
    {name = "a_m_y_motox_01", label = "Motox_01", Type = "Homme"},
    {name = "a_m_y_motox_02", label = "Motox_02", Type = "Homme"},
    {name = "a_m_y_musclbeac_01", label = "Musclbeac_01", Type = "Homme"},
    {name = "a_m_y_musclbeac_02", label = "Musclbeac_02", Type = "Homme"},
    {name = "a_m_y_polynesian_01", label = "Polynesian_01", Type = "Homme"},
    {name = "a_m_y_roadcyc_01", label = "Roadcyc_01", Type = "Homme"},
    {name = "a_m_y_runner_01", label = "Runner_01", Type = "Homme"},
    {name = "a_m_y_runner_02", label = "Runner_02", Type = "Homme"},
    {name = "a_m_y_salton_01", label = "Salton_01", Type = "Homme"},
    {name = "a_m_y_skater_01", label = "Skater_01", Type = "Homme"},
    {name = "a_m_y_skater_02", label = "Skater_02", Type = "Homme"},
    {name = "a_m_y_soucent_01", label = "Soucent_01", Type = "Homme"},
    {name = "a_m_y_soucent_02", label = "Soucent_02", Type = "Homme"},
    {name = "a_m_y_soucent_03", label = "Soucent_03", Type = "Homme"},
    {name = "a_m_y_soucent_04", label = "Soucent_04", Type = "Homme"},
    {name = "a_m_y_stbla_02", label = "Stbla_02", Type = "Homme"},
    {name = "a_m_y_stlat_01", label = "Stlat_01", Type = "Homme"},
    {name = "a_m_y_stwhi_01", label = "Stwhi_01", Type = "Homme"},
    {name = "a_m_y_stwhi_02", label = "Stwhi_02", Type = "Homme"},
    {name = "a_m_y_sunbathe_01", label = "Sunbathe_01", Type = "Homme"},
    {name = "a_m_y_surfer_01", label = "Surfer_01", Type = "Homme"},
    {name = "a_m_y_vindouche_01", label = "Vindouche_01", Type = "Homme"},
    {name = "a_m_y_vinewood_01", label = "Vinewood_01", Type = "Homme"},
    {name = "a_m_y_vinewood_02", label = "Vinewood_02", Type = "Homme"},
    {name = "a_m_y_vinewood_03", label = "Vinewood_03", Type = "Homme"},
    {name = "a_m_y_vinewood_04", label = "Vinewood_04", Type = "Homme"},
    {name = "a_m_y_yoga_01", label = "Yoga_01", Type = "Homme"},
    {name = "a_m_m_mlcrisis_01", label = "Mlcrisis_01", Type = "Homme"},
    {name = "a_m_y_gencaspat_01", label = "Gencaspat_01", Type = "Homme"},
    {name = "a_m_y_smartcaspat_01", label = "Smartcaspat_01", Type = "Homme"},
    {name = "cs_brad", label = "cs_brad", Type = "Homme"},
    {name = "cs_bradcadaver", label = "Bradcadaver", Type = "Homme"},
    {name = "cs_carbuyer", label = "Carbuyer", Type = "Homme"},
    {name = "cs_chengsr", label = "Chengsr", Type = "Homme"},
    {name = "cs_chrisformage", label = "Chrisformage", Type = "Homme"},
    {name = "cs_clay", label = "Clay", Type = "Homme"},
    {name = "cs_dale", label = "Dale", Type = "Homme"},
    {name = "cs_davenorton", label = "Davenorton", Type = "Homme"},
    {name = "cs_debra", label = "Debra", Type = "Homme"},
    {name = "cs_devin", label = "Devin", Type = "Homme"},
    {name = "cs_dom", label = "Dom", Type = "Homme"},
    {name = "cs_dreyfuss", label = "Dreyfuss", Type = "Homme"},
    {name = "cs_drfriedlander", label = "Drfriedlander", Type = "Homme"},
    {name = "cs_fabien", label = "Fabien", Type = "Homme"},
    {name = "cs_fbisuit_01", label = "cs_fbisuit_01", Type = "Homme"},
    {name = "cs_hunter", label = "Hunter", Type = "Homme"},
    {name = "cs_jimmyboston", label = "Jimmyboston", Type = "Homme"},
    {name = "cs_jimmydisanto", label = "Jimmydisanto", Type = "Homme"},
    {name = "cs_joeminutema", label = "Joeminutema", Type = "Homme"},
    {name = "cs_johnnyklebitz", label = "Johnnyklebitz", Type = "Homme"},
    {name = "cs_josef", label = "Josef", Type = "Homme"},
    {name = "cs_josh", label = "Josh", Type = "Homme"},
    {name = "cs_lazlow", label = "Lazlow", Type = "Homme"},
    {name = "cs_lazlow_2", label = "Lazlow_2", Type = "Homme"},
    {name = "cs_manuel", label = "Manuel", Type = "Homme"},
    {name = "cs_martinmadrazo", label = "Martinmadrazo", Type = "Homme"},
    {name = "cs_movpremmale", label = "Movpremmale", Type = "Homme"},
    {name = "cs_mrk", label = "Mrk", Type = "Homme"},
    {name = "cs_nervousron", label = "Nervousron", Type = "Homme"},
    {name = "cs_nigel", label = "Nigel", Type = "Homme"},
    {name = "cs_old_man1a", label = "Old_man1a", Type = "Homme"},
    {name = "cs_old_man2", label = "Old_man2", Type = "Homme"},
    {name = "cs_omega", label = "Omega", Type = "Homme"},
    {name = "cs_orleans", label = "Orleans", Type = "Homme"},
    {name = "cs_paper", label = "Paper", Type = "Homme"},
    {name = "cs_priest", label = "Pretre", Type = "Homme"},
    {name = "cs_russiandrunk", label = "Russiandrunk", Type = "Homme"},
    {name = "cs_siemonyetarian", label = "Siemonyetarian", Type = "Homme"},
    {name = "cs_solomon", label = "Solomon", Type = "Homme"},
    {name = "cs_stevehains", label = "Stevehains", Type = "Homme"},
    {name = "cs_stretch", label = "Stretch", Type = "Homme"},
    {name = "cs_taostranslator", label = "Taostranslator", Type = "Homme"},
    {name = "cs_tenniscoach", label = "Tenniscoach", Type = "Homme"},
    {name = "cs_tom", label = "Tom", Type = "Homme"},
    {name = "cs_tomepsilon", label = "Tomepsilon", Type = "Homme"},
    {name = "cs_tracydisanto", label = "Tracydisanto", Type = "Homme"},
    {name = "cs_wade", label = "Wade", Type = "Homme"},
    {name = "cs_zimbor", label = "Zimbor", Type = "Homme"},
    {name = "csb_agent", label = "Agent", Type = "Homme"},
    {name = "csb_alan", label = "Alan", Type = "Homme"},
    {name = "csb_anton", label = "Anton", Type = "Homme"},
    {name = "csb_avon", label = "Avon", Type = "Homme"},
    {name = "csb_bogdan", label = "Bogdan", Type = "Homme"},
    {name = "csb_burgerdrug", label = "Burgerdrug", Type = "Homme"},
    {name = "csb_car3guy1", label = "Car3guy1", Type = "Homme"},
    {name = "csb_car3guy2", label = "Car3guy2", Type = "Homme"},
    {name = "csb_cletus", label = "Cletus", Type = "Homme"},
    {name = "csb_customer", label = "Customer", Type = "Homme"},
    {name = "csb_dix", label = "Dix", Type = "Homme"},
    {name = "csb_englishdave", label = "Tnglishdave", Type = "Homme"},
    {name = "csb_fos_rep", label = "Fos_rep", Type = "Homme"},
    {name = "csb_g", label = "csb_g", Type = "Homme"},
    {name = "csb_groom", label = "Groom", Type = "Homme"},
    {name = "csb_grove_str_dlr", label = "Grove_str_dlr", Type = "Homme"},
    {name = "csb_hugh", label = "Hugh", Type = "Homme"},
    {name = "csb_imran", label = "Imran", Type = "Homme"},
    {name = "csb_jackhowitzer", label = "Jackhowitzer", Type = "Homme"},
    {name = "csb_janitor", label = "Janitor", Type = "Homme"},
    {name = "csb_money", label = "csb_money", Type = "Homme"},
    {name = "csb_mp_agent14", label = "Agent14", Type = "Homme"},
    {name = "csb_oscar", label = "Oscar", Type = "Homme"},
    {name = "csb_popov", label = "Popov", Type = "Homme"},
    {name = "csb_porndudes", label = "csb_porndudes", Type = "Homme"},
    {name = "csb_prologuedriver", label = "Prologuedriver", Type = "Homme"},
    {name = "csb_ramp_hic", label = "Ramp_hic", Type = "Homme"},
    {name = "csb_ramp_hipster", label = "Ramp_hipster", Type = "Homme"},
    {name = "csb_reporter", label = "Reporter", Type = "Homme"},
    {name = "csb_roccopelosi", label = "Roccopelosi", Type = "Homme"},
    {name = "csb_sol", label = "csb_sol", Type = "Homme"},
    {name = "csb_talcc", label = "csb_talcc", Type = "Homme"},
    {name = "csb_talmm", label = "csb_talmm", Type = "Homme"},
    {name = "csb_tonyprince", label = "csb_tonyprince", Type = "Homme"},
    {name = "csb_undercover", label = "Undercover", Type = "Homme"},
    {name = "csb_vagspeak", label = "Vagspeak", Type = "Homme"},
    {name = "csb_avery", label = "Avery", Type = "Homme"},
    {name = "csb_brucie2", label = "Brucie2", Type = "Homme"},
    {name = "csb_thornton", label = "Thornton", Type = "Homme"},
    {name = "csb_tomcasino", label = "Tomcasino", Type = "Homme"},
    {name = "mp_m_avongoon", label = "Avongoon", Type = "Homme"},
    {name = "mp_m_claude_01", label = "Claude_01", Type = "Homme"},
    {name = "mp_m_cocaine_01", label = "Cocaine_01", Type = "Homme"},
    {name = "mp_m_counterfeit_01", label = "Counterfeit_01", Type = "Homme"},
    {name = "mp_m_exarmy_01", label = "Exarmy_01", Type = "Homme"},
    {name = "mp_m_execpa_01", label = "Execpa_01", Type = "Homme"},
    {name = "mp_m_forgery_01", label = "Forgery_01", Type = "Homme"},
    {name = "mp_m_freemode_01", label = "Freemode_01", Type = "Homme"},
    {name = "mp_m_g_vagfun_01", label = "Vagfun_01", Type = "Homme"},
    {name = "mp_m_meth_01", label = "Meth_01", Type = "Homme"},
    {name = "mp_m_weapexp_01", label = "Weapexp_01", Type = "Homme"},
    {name = "mp_m_execpa_01", label = "Execpa_01", Type = "Homme"},
    {name = "u_m_m_jesus_01", label = "Jesus", Type = "Homme"},
    {name = "u_m_y_juggernaut_01", label = "Robot", Type = "Homme"},
    {name = "u_m_y_rsranger_01", label = "Toy Story", Type = "Homme"},
    {name = "a_f_m_beach_01", label = "Beach_01", Type = "Femme"},
    {name = "a_f_m_bevhills_01", label = "Bevhills_01", Type = "Femme"},
    {name = "a_f_m_bevhills_02", label = "Bevhills_02", Type = "Femme"},
    {name = "a_f_m_bodybuild_01", label = "Bodybuild_01", Type = "Femme"},
    {name = "a_f_m_business_02", label = "Business_02", Type = "Femme"},
    {name = "a_f_m_downtown_01", label = "Downtown_01", Type = "Femme"},
    {name = "a_f_m_eastsa_01", label = "Eastsa_01", Type = "Femme"},
    {name = "a_f_m_eastsa_02", label = "Eastsa_02", Type = "Femme"},
    {name = "a_f_m_fatbla_01", label = "Fatbla_01", Type = "Femme"},
    {name = "a_f_m_fatcult_01", label = "Fatcult_01", Type = "Femme"},
    {name = "a_f_m_fatwhite_01", label = "Fatwhite_01", Type = "Femme"},
    {name = "a_f_m_ktown_01", label = "Ktown_01", Type = "Femme"},
    {name = "a_f_m_ktown_02", label = "Ktown_02", Type = "Femme"},
    {name = "a_f_m_prolhost_01", label = "Prolhost_01", Type = "Femme"},
    {name = "a_f_m_salton_01", label = "Slton_01", Type = "Femme"},
    {name = "a_f_m_skidrow_01", label = "Skidrow_01", Type = "Femme"},
    {name = "a_f_m_soucent_01", label = "Soucent_01", Type = "Femme"},
    {name = "a_f_m_soucent_02", label = "Soucent_02", Type = "Femme"},
    {name = "a_f_m_soucentmc_01", label = "Soucentmc_01", Type = "Femme"},
    {name = "a_f_m_tourist_01", label = "Tourist_01", Type = "Femme"},
    {name = "a_f_m_tramp_01", label = "Tramp_01", Type = "Femme"},
    {name = "a_f_m_trampbeac_01", label = "a_f_m_trampbeac_01", Type = "Femme"},
    {name = "a_f_o_genstreet_01", label = "a_f_o_genstreet_01", Type = "Femme"},
    {name = "a_f_o_indian_01", label = "a_f_o_indian_01", Type = "Femme"},
    {name = "a_f_o_ktown_01", label = "a_f_o_ktown_01", Type = "Femme"},
    {name = "a_f_o_salton_01", label = "Salton_01", Type = "Femme"},
    {name = "a_f_o_soucent_01", label = "Soucent_01", Type = "Femme"},
    {name = "a_f_o_soucent_02", label = "Soucent_02", Type = "Femme"},
    {name = "a_f_y_beach_01", label = "Beach_01", Type = "Femme"},
    {name = "a_f_y_bevhills_01", label = "Bevhills_01", Type = "Femme"},
    {name = "a_f_y_bevhills_02", label = "Bevhills_02", Type = "Femme"},
    {name = "u_m_y_rsranger_01", label = "Toy Story", Type = "Femme"},
    {name = "a_f_y_bevhills_03", label = "Bevhills_03", Type = "Femme"},
    {name = "a_f_y_bevhills_04", label = "Bevhills_04", Type = "Femme"},
    {name = "a_f_y_business_01", label = "Business_01", Type = "Femme"},
    {name = "a_f_y_clubcust_02", label = "Clubcust_02", Type = "Femme"},
    {name = "a_f_y_eastsa_01", label = "Eastsa_01", Type = "Femme"},
    {name = "a_f_y_femaleagent", label = "Femaleagent", Type = "Femme"},
    {name = "a_f_y_topless_01", label = "Topless_01", Type = "Femme"},
    {name = "a_f_y_tourist_01", label = "Tourist_01", Type = "Femme"},
    {name = "csb_abigail", label = "Abigail", Type = "Femme"},
    {name = "csb_bryony", label = "Bryony", Type = "Femme"},
    {name = "mp_f_freemode_01", label = "Freemode_01", Type = "Femme"},
    {name = "mp_f_execpa_02", label = "Execpa_02", Type = "Femme"},
    {name = "mp_f_meth_01", label = "Meth_01", Type = "Femme"},
    {name = "u_f_y_poppymich_02", label = "Poppymich_02", Type = "Femme"},
    {name = "u_f_y_princess", label = "Princess", Type = "Femme"},
    {name = "u_f_y_corpse_02", label = "Corpse_02", Type = "Femme"},
} 

local haveTenueAdmin = false 
function tenueAdmin()
    if not haveTenueAdmin then 
        haveTenueAdmin = true
        SetPedMaxTimeUnderwater(PlayerPedId(), 150.0)
        TriggerEvent('skinchanger:getSkin', function(skin)
            local uniformObject
            if skin.sex == 0 then
                uniformObject = {
                    sex = 0,
                    bags_1 = 0, bags_2 = 0,
                    tshirt_1 = 23, tshirt_2 = 0,
                    torso_1 = 134, torso_2 = 0,
                    arms = 4,
                    pants_1 = 133, pants_2 = 1,
                    shoes_1 = 135, shoes_2 = 0,
                    mask_1 = 0, mask_2 = 0,
                    bproof_1 = 0, bproof_2 = 0,
                    helmet_1 = -1, helmet_2 = 0,
                    chain_1 = 0, chain_2 = 0,
                    decals_1 = 0, decals_2 = 0,
                    glasses_1 = -1, glasses_2 = 0,
                    watches_1 = -1, watches_2 = 0
                }
            else
                uniformObject = {
                    sex = 1,
                    bags_1 = 0, bags_2 = 0,
                    tshirt_1 = 135, tshirt_2 = 0,
                    torso_1 = 127, torso_2 = 0,
                    arms = 3,
                    pants_1 = 135, pants_2 = 1,
                    shoes_1 = 146, shoes_2 = 20,
                    mask_1 = 0, mask_2 = 0,
                    bproof_1 = 0, bproof_2 = 0,
                    helmet_1 = -1, helmet_2 = 0,
                    chain_1 = 0, chain_2 = 0,
                    decals_1 = 0, decals_2 = 0,
                    glasses_1 = -1, glasses_2 = 0,
                    watches_1 = -1, watches_2 = 0
                }
            end
            if uniformObject then
                TriggerEvent('skinchanger:loadClothes', skin, uniformObject)
            end
        end)
    else
        haveTenueAdmin = false
        SetPedMaxTimeUnderwater(PlayerPedId(), 10.0)
        ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin) TriggerEvent('skinchanger:loadSkin', skin) end)
    end
end


Administration.TableConfig = {
    GamerTagsPlayer = {},
    BlipsPlayer = {},
}

Administration.valeurUtils = {
    checknamejoueurs = false,
}
