var questions = {
    ['A']: [
        {
            "questionPhoto": 'question_1.png',
            "question": 'Pouvez-vous conduire sur la voie publique de cette manière ?',
            "a": 'Oui, s\'il n\'y a pas d\'autres véhicules à proximité.',
            "b": 'Non.',
            "c": 'Oui, si vous avez confiance en vos compétences.',
            "d": 'Oui, uniquement en dehors des agglomérations.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'Lorsque vous approchez du centre d\'un virage, vous devez',
            "a": 'déplacer vers l\'extérieur de la courbe.',
            "b": 'diminuer la manette des gaz.',
            "c": 'se déplacer vers l\'intérieur de la courbe',
            "d": 'appliquer le frein arrière.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_3.png',
            "question": 'À l\'approche d\'une intersection, vous devez sélectionner une position de voie pour',
            "a": 'réduisez votre distance de suivi.',
            "b": 'augmentez votre visibilité auprès des autres conducteurs de véhicules.',
            "c": 'augmentez votre vitesse et passez rapidement.',
            "d": 'faire tout ce qui précède.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Quelles sont les conditions pour porter un casque ?',
            "a": 'Le port du casque n\'est pas obligatoire lors de la conduite dans les rues de la ville.',
            "b": 'Tous les motocyclistes et passagers sont tenus de porter un casque en tout temps.',
            "c": 'Seuls les passagers sont tenus de porter un casque.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Saisir le frein avant ou bloquer le frein arrière',
            "a": 'Est le meilleur moyen d\'arrêter en cas d\'urgence.',
            "b": 'C\'est le meilleur moyen de ralentir quand les rues sont mouillées.',
            "c": 'Peut bloquer les freins.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Les passagers à moto doivent',
            "a": 'Devrait s\'asseoir le plus en avant possible sans vous encombrer.',
            "b": 'Mettre les pieds au sol lorsque la moto est à l\'arrêt.',
            "c": 'Ne pas rouler sans dossier.',
            "correctAnswer": 'A',
        },
        {
            "question": 'Lorsque vous roulez avec un groupe de motocyclistes, une formation en quinconce',
            "a": 'Doit être utilisé lors de la conduite dans les virages.',
            "b": 'Est recommandé en tout temps.',
            "c": 'Ne doit pas être utilisé à l\'entrée ou à la sortie d\'une autoroute.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Vous devez actionner l\'interrupteur de coupure du moteur et serrer l\'embrayage lorsque ',
            "a": 'L\'accélérateur est bloqué et vous ne pouvez pas le libérer.',
            "b": 'Vous commencez à perdre le contrôle dans une courbe.',
            "c": 'La moto commence à vaciller.',
            "correctAnswer": 'A',
        },

        {
            "question": 'Avant de changer de voie sur une route à plusieurs voies, vous devez vérifier',
            "a": 'la voie à côté de vous et la voie éloignée.',
            "b": 'seulement la voie la plus éloignée.',
            "c": 'votre signal lumineux.',
            "d": 'seulement la voie à côté de vous.',
            "correctAnswer": 'A',
        },
        {
            "question": 'Lorsque vous roulez en groupe, la meilleure formation est la formation ___.',
            "a": 'En Y.',
            "b": 'cote à cote.',
            "c": 'décalé.',
            "d": 'En forme de V.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Lorsqu\'il effectue un virage lent et serré, le motard doit',
            "a": 'penchez-vous dans le sens opposé de la moto.',
            "b": 'se pencher vers l\'avant de la moto.',
            "c": 'penchez-vous dans la même direction que la moto.',
            "d": 'garder son corps droit tout en penchant la moto.',
            "correctAnswer": 'D',
        },
        {
            "question": 'S\'il y a du trafic venant en sens inverse et que vous dépassez une file de voitures en stationnement, quelle position de voie devriez-vous choisir ?',
            "a": 'Centre',
            "b": 'Droite',
            "c": 'Centre ou droite',
            "d": 'Gauche',
            "correctAnswer": 'A',
        },
        {
            "question": 'La plupart de la puissance d\'arrêt de vos motos est fournie par',
            "a": 'le frein arrière.',
            "b": 'les freins avant et arrière de manière égale.',
            "c": 'l\'embrayage.',
            "d": 'le frein avant.',
            "correctAnswer": 'D',
        },
        {
            "question": 'Si votre moto commence à vaciller, la meilleure chose à faire est de',
            "a": 'freiner rapidement.',
            "b": 'fermez progressivement la manette des gaz.',
            "c": 'saisir fermement le guidon et voler l\'oscillation.',
            "d": 'accélérer hors de l\'oscillation.',
            "correctAnswer": 'C',
        },
        {
            "question": "Les surfaces qui offrent peu de traction pour une moto incluent",
            "a": 'voies peu fréquentées.',
            "b": 'route de graviers.',
            "c": 'marques de pneus, là où d\'autres véhicules ont voyagé.',
            "d": 'chaussée qui est chaude du soleil.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Augmentez votre sécurité la nuit en',
            "a": 'en utilisant les phares de la voiture qui vous précède pour vous aider à voir.',
            "b": 'augmenter votre distance de suivi.',
            "c": 'rouler avec vos feux de route.',
            "d": 'faire tout ce qui précède.',
            "correctAnswer": 'D',
        },
        {
            "question": 'Lorsque vous suivez un véhicule, vous devez maintenir une distance de suivi de ___ secondes.',
            "a": 'deux',
            "b": 'trois',
            "c": 'quatres',
            "d": 'cinq',
            "correctAnswer": 'A',
        },
        {
            "question": 'Dans une voie de circulation, combien de positions de voie y a-t-il pour une moto ?',
            "a": '1',
            "b": '2',
            "c": '3',
            "d": '4',
            "correctAnswer": 'C',
        },
    ],
    ['B']: [
        {
            "questionPhoto": 'question_1.png',
            "question": 'Faut-il freiner dans une telle situation ?',
            "a": 'Oui, car il y a suffisamment de distance pour freiner.',
            "b": 'Non, car dans un instant le feu passera au vert.',
            "c": 'Non.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'Pouvez-vous vous arrêter sur cette partie du trottoir ?',
            "a": 'Oui mais seulement quand la police nous arrête.',
            "b": 'Oui.',
            "c": 'Oui, un maximum de 5 minutes.',
            "d": 'Non.',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": 'question_3.png',
            "question": 'Pouvez-vous faire un virage à gauche dans cette situation ?',
            "a": 'Oui.',
            "b": 'Non.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_4.png',
            "question": 'Pouvez-vous tourner à droite à ce point sans vous arrêter ?',
            "a": 'Oui, lorsque les véhicules ne viennent pas du côté gauche',
            "b": 'Non, le panneau oblige le véhicule à s\'arrêter absolument.',
            "c": 'Oui, ce signe signifie ma priorité.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_5.png',
            "question": 'Quelle est la vitesse maximale que vous pouvez parcourir sur cette route ?',
            "a": '140 km/h',
            "b": '110 km/h',
            "c": '120 km/h',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_6.png',
            "question": 'La route montrée sur la photo peut-elle être parcourue dans les deux sens ?',
            "a": 'Oui, si cela ne compromet pas la sécurité des autres participants à la circulation.',
            "b": 'Non.',
            "c": 'Oui.',
            "d": 'Seuls les taxis peuvent se déplacer dans la direction opposée',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_7.png',
            "question": 'Pouvez-vous tourner à gauche à ce stade ?',
            "a": 'Oui.',
            "b": 'Non.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_8.png',
            "question": 'Lequel de ces marquages au sol sépare deux voies circulant dans le même sens ?',
            "a": 'A',
            "b": 'B',
            "c": 'Aucune de ces réponses',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_9.png',
            "question": 'Ce signe signifie :',
            "a": 'Passage piéton devant',
            "b": 'Les piétons ne doivent pas traverser ici',
            "c": 'Piétons marchant le long de la route devant',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_10.png',
            "question": 'Ce signe signifie :',
            "a": 'Ne pas entrer.',
            "b": 'Stationnement réservé aux personnes handicapées.',
            "c": 'Cédez le passage.',
            "correctAnswer": 'A',
        },
        {
            "question": 'Pouvez-vous dépasser un autre véhicule à l\'approche d\'un virage ou d\'une côte ?',
            "a": 'Oui, mais vous ne pouvez passer que par la droite.',
            "b": 'Non, jamais.',
            "c": 'Oui, mais seulement s\'il y a suffisamment d\'espace.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Lequel des endroits suivants est un demi-tour autorisé ?',
            "a": 'Sur le passage à niveau',
            "b": 'À travers une double ligne jaune',
            "c": 'Dans une rue à sens unique',
            "correctAnswer": 'B',
        },
        {
            "question": 'Vous devriez réduire votre vitesse de moitié lorsque la route est ___.',
            "a": 'mouillée',
            "b": 'glacée',
            "c": 'pbourré de neige',
            "correctAnswer": 'C',
        },
        {
            "question": 'Lorsque vous conduisez dans le brouillard, la pluie ou la neige, utilisez ___.',
            "a": 'feux de croisement',
            "b": 'feux de brouillard seulement',
            "c": 'feux de route',
            "correctAnswer": 'A',
        },
        {
            "question": 'Une ligne médiane jaune brisée signifie que :',
            "a": 'Le dépassement n\'est pas autorisé.',
            "b": 'Le dépassement par la gauche est autorisé lorsque la voie à suivre est dégagée.',
            "c": 'Le dépassement par la droite est autorisé lorsque la voie à suivre est dégagée.',
            "correctAnswer": 'B',
        },
        {
            "question": 'L\'alcool est',
            "a": 'A stimulant.',
            "b": 'Cool',
            "c": 'Un dépresseur.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Avant de changer de voie, vous devriez vérifier vos rétroviseurs et',
            "a": 'Regard par-dessus ton épaule',
            "b": 'Ne regardez jamais par-dessus votre épaule droite',
            "c": 'Ralentissez toujours dans votre voie de circulation',
            "correctAnswer": 'A',
        },
        
    ],
    ['C']: [
        {
            "question": 'Laquelle des actions suivantes ne devriez-vous PAS faire si vous rencontrez une défaillance de pneu ?',
            "a": 'Sachez qu\'un pneu est défaillant.',
            "b": 'Freinez fort et immédiatement.',
            "c": 'Tenez fermement le volant.',
            "d": 'Ne touchez pas à la pédale de frein.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Des drapeaux ou des feux sont requis sur les charges en saillie qui s\'étendent',
            "a": '56 pouces ou plus au-delà de la carrosserie arrière.',
            "b": '3 pieds ou plus au-delà du corps arrière.',
            "c": '4 pieds ou plus au-delà du corps arrière.',
            "d": '6 pieds ou plus au-delà du corps arrière.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Laquelle de ces valeurs correspond à la distance d\'arrêt totale ?',
            "a": 'Distance de réaction + distance de freinage',
            "b": 'Distance de réaction + distance de freinage + distance de signal',
            "c": 'Distance de perception + distance de réaction + distance de freinage',
            "d": 'Distance de perception + distance de réaction',
            "correctAnswer": 'C',
        },
        {
            "question": 'Pour vous aider à rester vigilant et en sécurité pendant la conduite, vous devez',
            "a": 'buvez du café si vous êtes somnolent.',
            "b": 'évitez les médicaments dont les étiquettes d\'avertissement mentionnent la somnolence.',
            "c": 'prenez un whisky pour vous préparer.',
            "d": 'baissez vos fenêtres pour prendre l\'air.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Un extincteur de type A : B : C est conçu pour fonctionner sur quels types de feux ?',
            "a": 'Bois, papier et tissu',
            "b": 'De l\'essence',
            "c": 'Électrique',
            "d": 'Tout ce qui précède',
            "correctAnswer": 'D',
        },
    ],
}